import type { Locale } from "./types";

type Field = { label: string; body: string };
interface ContactCopy { intro: string; labels: string[]; titles: string[]; statement: string; formatsIntro: string; targets: { title: string; fields: Field[]; note: string }[]; formats: { title: string; fields: Field[]; note: string }[]; applications: Field[]; details: Field[]; preparation: Field[]; captions: string[]; footerTitle: string; footerBody: string; quick: { title: string; note: string; capabilitiesTitle: string; emailLabel: string; copy: string; copied: string; details: string } }

export const contactProfileUrl = "https://ukmsarjana.ukm.my/main/lihat_profil/SzAyNDQ3OA==";
export const contactEmail = "chawjk@ukm.edu.my";
export const contactContent: Record<Locale, ContactCopy> = {
  "en": {
    intro: "The HI Lab welcomes aligned collaboration across manufacturing, healthcare, civic systems and postgraduate research.",
    labels: ["Partner with us", "Collaboration targets", "Collaboration formats", "Student applications", "Contact information", "Contact preparation", "Visuals"],
    titles: ["Begin with an aligned research or deployment goal", "Four groups, each with a defined working boundary", "Three ways to begin", "Long-term postgraduate recruitment", "Confirmed public details", "What makes a useful first conversation", "Collaboration in context"],
    statement: "The HI Lab balances rigorous academic research with strong commercial viability. We welcome manufacturing enterprises, clinical institutions and prospective scholars working across predictive systems, diagnostics, Edge Computing and LLM orchestration.",
    formatsIntro: "Each format retains its suitable scenario, mutual investment and confirmation process.",
    targets: [{"title": "Tech & Manufacturing Enterprises", "fields": [{"label": "DIRECTION", "body": "Predictive Maintenance & Edge Vision"}, {"label": "SCOPE & PREREQUISITES", "body": "B2B industrial grants and real-world hardware testing environments."}], "note": "Proven deployment track record."}, {"title": "Hospitals & Public Health Agencies", "fields": [{"label": "DIRECTION", "body": "Digital Health & Disease Modeling"}, {"label": "SCOPE & PREREQUISITES", "body": "Strict data privacy and federated learning protocols."}], "note": "Algorithmic R&D, not clinical advice."}, {"title": "Government & Civic Agencies", "fields": [{"label": "DIRECTION", "body": "AI-RAG Agents & Digital Concierges"}, {"label": "SCOPE & PREREQUISITES", "body": "Access to internal civic knowledge bases or policy APIs."}], "note": "Multilingual support is available."}, {"title": "Prospective Students (PhD/MSc)", "fields": [{"label": "DIRECTION", "body": "Machine Learning, Computer Vision & LLM Research"}, {"label": "SCOPE & PREREQUISITES", "body": "Foundation in Python, Mathematics and hands-on Machine Learning."}], "note": "Inquiries accepted year-round."}],
    formats: [{"title": "Industrial Tech Transfer", "fields": [{"label": "SUITABLE SCENARIO", "body": "Enterprises facing automation, visual inspection or energy-efficiency challenges."}, {"label": "MUTUAL INVESTMENT", "body": "Enterprise provides funding and raw data; the lab delivers algorithms."}, {"label": "CONFIRMATION PROCESS", "body": "Needs Assessment → NDA → Tech Validation → Project Kick-off"}], "note": "PI assesses feasibility."}, {"title": "Joint Academic Research & Grants", "fields": [{"label": "SUITABLE SCENARIO", "body": "Universities or institutes pursuing Q1 publications and national or international grants."}, {"label": "MUTUAL INVESTMENT", "body": "Share core data, research personnel and computing clusters."}, {"label": "CONFIRMATION PROCESS", "body": "Academic Alignment → Proposal Drafting → Joint Submission"}], "note": "Cross-border work is welcomed."}, {"title": "Postgraduate Talent Recruitment", "fields": [{"label": "SUITABLE SCENARIO", "body": "Students pursuing advanced AI degrees, publications or careers in technology."}, {"label": "MUTUAL INVESTMENT", "body": "Full-time research commitment; the lab provides supervision, hardware and publishing support."}, {"label": "CONFIRMATION PROCESS", "body": "CV & Proposal → Interview → Faculty Admission"}], "note": "Training spans theory and deployment."}],
    applications: [{"label": "RECRUITMENT TARGET", "body": "Self-motivated PhD and Master by Research applicants from CS, EE or Data Science."}, {"label": "DIRECTION", "body": "Edge AI Vision Deployment, LLM-Agent Orchestration and Medical Image Analytics."}, {"label": "APPLICATION METHOD", "body": "Send a CV, academic transcripts and a one-page preliminary proposal to chawjk@ukm.edu.my. Subject line: [PhD/MSc Application - Your Name]."}, {"label": "CURRENT STATUS", "body": "Long-term open recruitment. Official intakes follow the UKM academic calendar."}],
    details: [{"label": "CONTACT PERSON", "body": "Dr. Chaw Jun Kit / Principal Investigator"}, {"label": "EMAIL", "body": contactEmail}, {"label": "LOCATION", "body": "Institute of Visual Informatics, UKM, 43600 Bangi, Selangor, Malaysia"}, {"label": "PROFILE", "body": "UKMsarjana Academic Profile"}],
    preparation: [{"label": "WHAT TO PROVIDE", "body": "Enterprise inquiries should describe the business context, technical pain point, data volume and hardware constraints. Academic and student inquiries should include education, project outcomes and technical skills."}, {"label": "MATTERS WE RESPOND TO", "body": "Industrial grant alignment, joint academic proposals, R&D consulting and postgraduate admissions. Vague proofs of concept without data and unrelated administrative requests are outside scope."}, {"label": "EXPECTED RESPONSE", "body": "All inquiries receive an initial feasibility screening. Highly aligned requests typically receive a response within 3 to 5 business days. No response within two weeks indicates no current capacity."}],
    captions: ["Research review", "Prototype collaboration"],
    footerTitle: "Partner with us.",
    footerBody: "Research partnerships, enterprise collaboration and postgraduate opportunities begin with a focused, evidence-backed inquiry.",
    quick: { title: "Quick contact", note: "Tell us who you are and what collaboration you are seeking — inquiries typically receive a response within 3–5 business days.", capabilitiesTitle: "Our Capabilities", emailLabel: "Email", copy: "Copy email", copied: "Copied", details: "View full contact details" },
  },
  "zh-CN": {
    intro: "怡合智能欢迎制造、医疗、民生系统与研究生研究领域中目标一致的合作。",
    labels: ["与我们合作", "合作对象", "合作形式", "学生申请", "联系信息", "沟通说明", "协作现场"],
    titles: ["从一致的研究或部署目标开始", "四类合作对象，各有明确的合作边界", "三种合作起点", "长期研究生招募", "已确认的公开联系信息", "让首次沟通更有成效", "合作场景"],
    statement: "怡合智能兼顾严谨的学术研究与扎实的商业可行性。我们欢迎制造企业、临床机构，以及从事预测系统、辅助诊断、边缘计算和大语言模型编排研究的未来学者开展合作。",
    formatsIntro: "每种合作形式都明确适用场景、双方投入与确认流程。",
    targets: [{"title": "科技 / 制造企业", "fields": [{"label": "合作方向", "body": "预测性维护与边缘视觉"}, {"label": "范围与前提", "body": "提供企业合作基金和真实硬件测试环境。"}], "note": "已有成功部署的可靠实绩。"}, {"title": "医院与公共卫生机构", "fields": [{"label": "合作方向", "body": "数字健康与疾病建模"}, {"label": "范围与前提", "body": "严格遵守数据隐私与联邦学习协议。"}], "note": "我们提供算法研发，不直接提供临床建议。"}, {"title": "政府与民生服务机构", "fields": [{"label": "合作方向", "body": "检索增强生成（RAG）智能体与数字礼宾"}, {"label": "范围与前提", "body": "可访问内部民生知识库或政策 API。"}], "note": "可提供多语言支持。"}, {"title": "意向学生（博士 / 硕士）", "fields": [{"label": "合作方向", "body": "机器学习、计算机视觉、智能体人工智能与大语言模型（LLM）研究"}, {"label": "范围与前提", "body": "具备扎实的 Python、数学基础和机器学习实践能力。"}], "note": "全年接受咨询。"}],
    formats: [{"title": "产业技术转移（联合研发）", "fields": [{"label": "适用场景", "body": "在自动化、视觉检测或能源效率方面面临具体挑战的企业。"}, {"label": "双方投入", "body": "企业提供资金（如产业基金）和原始数据；实验室交付算法。"}, {"label": "确认流程", "body": "需求评估 → 保密协议 → 技术验证 → 项目启动。"}], "note": "由课题负责人直接评估项目可行性。"}, {"title": "联合学术研究与科研基金", "fields": [{"label": "适用场景", "body": "以一区期刊论文和国家级或国际科研基金为目标的大学或研究机构。"}, {"label": "双方投入", "body": "共享核心数据、研究人员与计算集群。"}, {"label": "确认流程", "body": "学术方向对齐 → 申请书起草 → 联合提交。"}], "note": "非常欢迎跨国与跨学科合作。"}, {"title": "研究生人才招募", "fields": [{"label": "适用场景", "body": "希望攻读人工智能高阶学位、发表一流论文或进入大型科技企业发展的优秀学生。"}, {"label": "双方投入", "body": "全职投入研究；实验室提供指导、硬件与论文发表支持。"}, {"label": "确认流程", "body": "提交简历 / 研究计划 → 面试 → 学院正式录取。"}], "note": "提供从理论到工程部署的系统化训练。"}],
    captions: ["研究评审", "原型协作"],
    footerTitle: "与我们合作。",
    footerBody: "研究伙伴关系、企业合作与研究生机会，始于目标明确、有据可依的咨询。",
    applications: [{"label": "招募对象", "body": "面向计算机科学、电气工程或数据科学背景，且具备高度自驱力的研究型博士与硕士申请人。"}, {"label": "方向", "body": "边缘人工智能视觉部署、大语言模型智能体编排与医学影像分析。"}, {"label": "申请方式", "body": "请将详细简历、成绩单和一页初步研究计划发送至 chawjk@ukm.edu.my。邮件主题：［博士 / 硕士申请 - 您的姓名］。"}, {"label": "当前状态", "body": "长期开放招募（正式入学时间以马来西亚国民大学校历为准）。"}],
    details: [{"label": "联系人", "body": "周俊杰博士（课题负责人）"}, {"label": "邮箱", "body": contactEmail}, {"label": "地点", "body": "马来西亚雪兰莪州万宜 43600，马来西亚国民大学（UKM）视觉信息学研究所（IVI）。"}, {"label": "社媒/预约", "body": "访问学术主页"}],
    quick: { title: "快速联系", note: "请在邮件中说明您的身份与希望开展的合作，咨询通常会在 3–5 个工作日内收到回复。", capabilitiesTitle: "我们的能力领域", emailLabel: "邮箱", copy: "复制邮箱", copied: "已复制", details: "查看完整联系信息" },
    preparation: [{"label": "联系时提供什么", "body": "企业咨询： 请简要说明业务背景、具体技术痛点、数据规模和硬件限制。学术 / 学生咨询： 请提供完整的教育背景、过往项目成果及核心技术栈清单。"}, {"label": "可响应哪些事项", "body": "我们回复以下咨询： 产业基金匹配、联合学术研究计划、研发咨询与研究生招生。我们不回复以下咨询： 缺乏数据支撑、内容模糊的商业概念验证，或一般性的非学术 / 非产业行政咨询。"}, {"label": "预计回复说明", "body": "我们会对所有合作与入学申请进行初步可行性筛选。匹配度较高的咨询通常会在 3–5 个工作日内收到回复；若两周内未收到回复，则表示当前暂无能力承接所提合作。"}],
  },
};
