import type { Localized } from "./types";

export type ProjectCategoryId = "ai" | "edge" | "products" | "digital";

export interface DirectoryProject {
  id: string;
  title: string;
  shortTitle: string;
  purpose: string;
  paragraphs: [string, string];
  highlights: string[];
  features: string[];
  image: {
    src: string;
    width: number;
    height: number;
    alt: string;
    illustrative: boolean;
  };
}

export interface DirectoryCategory {
  id: ProjectCategoryId;
  title: string;
  description: string;
  projects: DirectoryProject[];
}

export const projectDirectory: Localized<DirectoryCategory[]> = {
  "zh-CN": [
    {
      id: "ai",
      title: "人工智能解决方案",
      description: "面向健康、公共服务与产业应用，交付预测模型、知识库、智能体与生成式应用。",
      projects: [
        {
          id: "P-03",
          title: "基于检索增强生成（RAG）的实时虚拟形象一体化数字礼宾系统",
          shortTitle: "数字礼宾",
          purpose: "通过可对话的数字人连接公共服务知识，让民生信息更容易获取。",
          paragraphs: ["智慧城市与旅游服务需要便于交互的信息入口。项目围绕民生政策构建领域知识库，将检索增强生成与实时数字人结合，让访客通过自然对话提出问题。", "多语言交互帮助不同访客获取公共服务信息，实时渲染与检索流程共同支撑服务响应，为市民咨询与旅游接待提供可扩展的服务触点。"],
          highlights: ["领域知识库", "多语言交互"],
          features: ["政策知识检索", "多语言对话", "实时数字人"],
          image: {"src": "/images/hil-site/projects/catalog/civic-service-photo.webp", "width": 1536, "height": 1024, "alt": "基于检索增强生成（RAG）的实时虚拟形象一体化数字礼宾系统写实概念配图", "illustrative": true},
        },
        {
          id: "P-06",
          title: "面向预测性维护的能源消耗预测",
          shortTitle: "能耗预测",
          purpose: "利用工厂传感器数据预测能耗变化，为设备维护安排提供依据。",
          paragraphs: ["制造现场的突发故障与能源浪费，往往与事后维护有关。项目采集并清洗高频传感器数据，通过深度学习与自适应双蒸馏方法，分析能耗变化和潜在故障信号。", "可视分析仪表板将预测信息呈现给车间管理人员，辅助判断设备状态与安排维护。应用重点是让生产团队更早关注异常，并结合现场情况调整维护计划。"],
          highlights: ["高频传感器数据", "可视分析仪表板"],
          features: ["能耗预测", "异常识别", "维护可视分析"],
          image: {"src": "/images/hil-site/projects/catalog/energy-monitoring-photo.webp", "width": 1536, "height": 1024, "alt": "面向预测性维护的能源消耗预测写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-01",
          title: "基于不平衡序列数据的非传染性疾病早期预测",
          shortTitle: "疾病早期预测",
          purpose: "面向不平衡医学序列数据改进建模方法，支持疾病早期预警研究。",
          paragraphs: ["非传染性疾病潜伏期长，医学数据中的样本分布不均也会影响预警模型。项目从临床数据中提取序列结构，研究针对这些特征的动态数据增强方法。", "通过交叉验证评估模型的早期预警表现，探索对少数样本更敏感的预测方式。研究希望为疾病风险识别提供方法基础，支持后续医学数据分析与验证。"],
          highlights: ["动态数据增强", "交叉验证"],
          features: ["序列特征分析", "动态数据增强", "预警模型评估"],
          image: {"src": "/images/hil-site/projects/catalog/clinical-research-photo.webp", "width": 1536, "height": 1024, "alt": "基于不平衡序列数据的非传染性疾病早期预测写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-02",
          title: "面向老年心理健康监测的面部表情识别",
          shortTitle: "老年情绪监测",
          purpose: "通过非接触式表情识别与对话交互，辅助关注老年人的情绪变化。",
          paragraphs: ["居家养老中的情绪变化不易被持续观察。项目建立老年人面部特征数据集，以多模态模型分析表情和情绪状态转移，并连接具有同理心的对话智能体。", "非接触式监测与对话反馈共同提供情绪线索，系统将心理预警推送给照护人员，帮助他们及时关注老人状态，并为进一步沟通与照护提供参考。"],
          highlights: ["情绪状态转移", "非接触式监测"],
          features: ["表情分析", "情绪状态建模", "照护预警"],
          image: {"src": "/images/hil-site/projects/catalog/elder-care-photo.webp", "width": 1536, "height": 1024, "alt": "面向老年心理健康监测的面部表情识别写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-04",
          title: "融合网络爬取与大语言模型的诈骗监测模型",
          shortTitle: "诈骗监测",
          purpose: "结合图像取证与语言理解，辅助发现多模态内容中的诈骗线索。",
          paragraphs: ["网络诈骗内容持续变化，仅靠关键词难以理解图像与文字中的欺诈意图。项目持续采集多模态样本，将图像取证方法与语言语义分析结合。", "联合分类器综合分析不同形式的信息，支持诈骗监测与早期预警。应用重点是从复杂网络内容中识别可疑线索，为后续核查提供更有针对性的参考。"],
          highlights: ["图像取证", "联合分类器"],
          features: ["多模态采集", "图文联合分类", "诈骗预警"],
          image: {"src": "/images/hil-site/projects/catalog/scam-analysis-photo.webp", "width": 1536, "height": 1024, "alt": "融合网络爬取与大语言模型的诈骗监测模型写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-05",
          title: "钉钉 AI 办公助手",
          shortTitle: "钉钉办公助手",
          purpose: "把任务、日程和会议提醒集中到钉钉，辅助团队处理日常协作。",
          paragraphs: ["日常工作中的任务遗漏与日程冲突会打断团队协作。办公助手集成于钉钉，将任务管理、日程安排和会议提醒放在同一工作入口，帮助员工跟进待办事项。", "通过自动化日常任务与事项提醒，助手把分散的办公步骤衔接到协同工作流。团队可以围绕已有日程组织工作，减少依赖人工记忆和重复操作的环节。"],
          highlights: ["任务管理", "事项提醒"],
          features: ["任务管理", "日程安排", "会议提醒"],
          image: {"src": "/images/hil-site/projects/catalog/office-assistant-photo.webp", "width": 1536, "height": 1024, "alt": "钉钉 AI 办公助手写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-06",
          title: "AI 智能健身助手",
          shortTitle: "智能健身助手",
          purpose: "结合个人健康信息与运动习惯提供健身建议，帮助用户跟进目标。",
          paragraphs: ["不同用户的身体状况和运动习惯，使通用训练计划难以贴合个人需要。项目汇集健康与运动信息，形成用户画像，并据此推荐适合个人情况的健身计划。", "从目标设定到执行反馈，助手将建议与用户的实际行动连接起来，帮助用户持续跟进训练安排。应用重点是提供更贴近个人需求的运动指导体验。"],
          highlights: ["用户画像", "目标设定"],
          features: ["健康信息整合", "健身计划推荐", "目标与反馈"],
          image: {"src": "/images/hil-site/projects/catalog/fitness-coach-photo.webp", "width": 1536, "height": 1024, "alt": "AI 智能健身助手写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-07",
          title: "AI 艺术图像生成平台",
          shortTitle: "艺术图像生成",
          purpose: "让用户通过文字描述和风格选择创作图像，降低个性化表达门槛。",
          paragraphs: ["个性化艺术创作通常需要掌握专业工具。平台提供文本描述与风格选择入口，将用户的创作想法带入图像生成流程，支持不同绘画风格与主题。", "生成内容可以在平台内展示与互动，让创作和交流形成连续体验。用户能够以更直接的方式表达想法，并围绕不同风格探索自己的视觉作品。"],
          highlights: ["文本描述", "风格选择"],
          features: ["文字输入", "绘画风格选择", "作品展示互动"],
          image: {"src": "/images/hil-site/projects/catalog/art-creation-photo.webp", "width": 1536, "height": 1024, "alt": "AI 艺术图像生成平台写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-10",
          title: "TikTok AI 自动化获客与销售系统",
          shortTitle: "智能获客与销售",
          purpose: "分析短视频评论中的潜在线索，连接客户跟进与销售工作流程。",
          paragraphs: ["短视频评论中的需求线索分散，人工发现与跟进较为繁琐。项目围绕视频和评论采集，通过智能分析识别潜在线索，将内容信息连接到获客流程。", "线索追踪与预设消息衔接后续沟通，使发现、分析和跟进形成连续步骤。应用面向销售团队的线索管理需求，帮助组织日常跟进工作与客户互动。"],
          highlights: ["潜在线索", "线索追踪"],
          features: ["视频与评论采集", "线索分析", "跟进管理"],
          image: {"src": "/images/hil-site/projects/catalog/sales-workflow-photo.webp", "width": 1536, "height": 1024, "alt": "TikTok AI 自动化获客与销售系统写实概念配图", "illustrative": true},
        },
      ],
    },
    {
      id: "edge",
      title: "边缘智能",
      description: "将计算机视觉与轻量模型部署到设备端，交付实时识别与软硬件集成方案。",
      projects: [
        {
          id: "P-05",
          title: "智慧零售：边缘人工智能生鲜识别系统",
          shortTitle: "生鲜识别",
          purpose: "把轻量视觉模型集成到零售称重秤，辅助自动识别水果和蔬菜。",
          paragraphs: ["超市生鲜结账依赖人工识别与输入商品代码，容易出现排队和录入差错。项目建立经农业分类学专家验证的图像数据集，训练适合边缘芯片的轻量视觉模型。", "模型与物联网称重硬件集成，在设备端完成实时识别，连接商品识别与称重流程。应用旨在减少人工录入步骤，让生鲜结账与商品管理更顺畅。"],
          highlights: ["轻量视觉模型", "实时识别"],
          features: ["生鲜识别", "端侧推理", "称重硬件集成"],
          image: {"src": "/images/hil-site/projects/catalog/produce-scale-photo.webp", "width": 1536, "height": 1024, "alt": "智慧零售：边缘人工智能生鲜识别系统写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-03",
          title: "面向农业 4.0、具备无线充电能力的自主无人机测绘",
          shortTitle: "无人机农业测绘",
          purpose: "结合自主航线、无线充电和图像拼接，支持种植园持续巡检与测绘。",
          paragraphs: ["大型种植园巡检受人工投入和无人机续航限制，影响数据采集频率。项目配置自主航线与无线充电站，并通过计算机视觉完成田间图像拼接。", "边缘端测绘与云端分析连接，形成可供农业管理使用的地图和指标。应用重点是支持持续的空中巡检，帮助管理人员掌握田间情况与空间信息。"],
          highlights: ["无线充电站", "田间图像拼接"],
          features: ["自主航线", "无线充电", "图像拼接", "农业测绘"],
          image: {"src": "/images/hil-site/projects/catalog/agriculture-drone-photo.webp", "width": 1536, "height": 1024, "alt": "面向农业 4.0、具备无线充电能力的自主无人机测绘写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-08",
          title: "AI 人脸识别门禁系统",
          shortTitle: "人脸识别门禁",
          purpose: "把人脸身份核验连接到访问控制，辅助门禁和安防管理。",
          paragraphs: ["门禁管理需要将身份核验与通行权限有效连接。项目采集并比对人脸身份信息，将识别结果接入访问控制，衔接既有的安防监控与门禁管理流程。", "人员核验与通行处理在同一流程中完成，为日常安防管理提供更直接的操作路径。应用面向需要人脸识别的访问场景，辅助组织身份验证与出入管理。"],
          highlights: ["身份核验", "访问控制"],
          features: ["人脸比对", "身份验证", "访问控制"],
          image: {"src": "/images/hil-site/projects/catalog/access-control-photo.webp", "width": 1536, "height": 1024, "alt": "AI 人脸识别门禁系统写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-09",
          title: "GTorque 游戏攻略助手",
          shortTitle: "游戏攻略助手",
          purpose: "理解游戏画面中的场景与任务，为玩家提供相应攻略和提示。",
          paragraphs: ["玩家在游戏推进过程中可能难以判断关键场景、任务或后续路径。助手利用图像识别和计算机视觉分析游戏画面，将识别内容关联到对应攻略。", "场景理解与攻略提示共同辅助玩家推进游戏，减少寻找相关说明时的信息切换。项目关注在实际游玩过程中提供有针对性的提示与辅助信息。"],
          highlights: ["图像识别", "攻略提示"],
          features: ["场景识别", "任务关联", "攻略提示"],
          image: {"src": "/images/hil-site/projects/catalog/game-guide-photo.webp", "width": 1536, "height": 1024, "alt": "GTorque 游戏攻略助手写实概念配图", "illustrative": true},
        },
      ],
    },
    {
      id: "products",
      title: "定制数字产品",
      description: "围绕行业需求构建网站、移动应用与服务平台，连接交易、推荐和用户互动。",
      projects: [
        {
          id: "P-07-11",
          title: "Merace 元宇宙游戏平台",
          shortTitle: "Merace 游戏平台",
          purpose: "连接平台货币、游戏道具与跨游戏资产管理，组织玩家交易体验。",
          paragraphs: ["游戏平台涉及货币、角色与道具等不同资产。Merace 围绕区块链游戏组织购买与使用流程，将多款游戏连接到同一平台，提供统一的资产操作入口。", "跨游戏资产管理与交易衔接玩家在不同游戏中的需求，让道具购买、资产查看和交易形成连续体验。平台重点是整合游戏内容及相应的交易流程。"],
          highlights: ["跨游戏资产管理", "交易流程"],
          features: ["平台货币使用", "角色道具购买", "跨游戏资产管理"],
          image: {"src": "/images/hil-site/projects/catalog/what_right1.webp", "width": 479, "height": 460, "alt": "Merace 元宇宙游戏平台展示图", "illustrative": false},
        },
        {
          id: "P-07-12",
          title: "保险业务智能服务与在线理赔平台",
          shortTitle: "保险服务与理赔",
          purpose: "整合产品查询、在线投保和理赔申请，让保险服务流程更连贯。",
          paragraphs: ["保险客户需要在产品了解、投保、咨询与理赔之间获取连续服务。平台整合保险产品和客户服务信息，将在线投保、智能客服与咨询入口连接起来。", "在线理赔申请和状态处理延伸了投保后的服务流程，帮助用户通过网页完成不同阶段的操作。应用重点是让信息查询、沟通与业务办理更便于衔接。"],
          highlights: ["在线投保", "在线理赔申请"],
          features: ["产品查询", "在线投保", "智能客服", "理赔申请"],
          image: {"src": "/images/hil-site/projects/catalog/insurance-service-photo.webp", "width": 1536, "height": 1024, "alt": "保险业务智能服务与在线理赔平台写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-13",
          title: "AI 社交电商 App",
          shortTitle: "社交电商",
          purpose: "将商品发现、购物分享与个性化推荐结合，连接用户互动和消费。",
          paragraphs: ["社交电商中的商品发现常与用户交流紧密相连。应用将新零售和社交互动整合到移动购物流程，让用户发现、购买商品，并分享自己的购物体验。", "好友推荐与用户互动为商品推荐提供信息，连接内容交流和精准营销。项目希望让用户在交流中发现适合自己的商品，形成连贯的社交购物体验。"],
          highlights: ["社交互动", "好友推荐"],
          features: ["商品发现", "购买流程", "购物分享", "商品推荐"],
          image: {"src": "/images/hil-site/projects/catalog/what_right3.webp", "width": 479, "height": 460, "alt": "AI 社交电商 App展示图", "illustrative": false},
        },
        {
          id: "P-07-14",
          title: "O2O 智能匹配与活动交友平台",
          shortTitle: "活动交友",
          purpose: "根据兴趣连接合适的人与活动，让匹配、交流和参与过程更顺畅。",
          paragraphs: ["用户寻找兴趣相近的朋友时，也需要方便地发现和参与活动。平台建立兴趣与智能匹配机制，将人与活动的选择连接起来，提供统一的互动入口。", "活动创建、管理与参与形成连续流程，并利用互动反馈优化匹配体验。应用重点是把找到合适的人与参加共同活动衔接起来，支持持续的社交交流。"],
          highlights: ["智能匹配", "互动反馈"],
          features: ["兴趣匹配", "活动创建", "活动管理", "参与互动"],
          image: {"src": "/images/hil-site/projects/catalog/what_right4.webp", "width": 479, "height": 460, "alt": "O2O 智能匹配与活动交友平台展示图", "illustrative": false},
        },
        {
          id: "P-07-15",
          title: "RiceUp 本地餐饮外卖平台",
          shortTitle: "RiceUp 餐饮外卖",
          purpose: "聚合附近餐饮、个性化推荐与用户评价，帮助用户发现并下单。",
          paragraphs: ["寻找附近餐饮与选择外卖时，用户需要兼顾口味、服务和其他人的反馈。RiceUp 聚合本地餐饮与外卖服务，将餐饮发现和下单放在同一平台。", "个性化推荐和用户评价辅助用户选择餐饮，反馈也用于改善后续发现体验。应用围绕浏览、选择、下单与评价组织流程，让本地用餐选择更方便。"],
          highlights: ["个性化推荐", "用户评价"],
          features: ["附近餐饮发现", "外卖下单", "个性化推荐", "用户评价"],
          image: {"src": "/images/hil-site/projects/catalog/food-delivery-photo.webp", "width": 1536, "height": 1024, "alt": "RiceUp 本地餐饮外卖平台写实概念配图", "illustrative": true},
        },
      ],
    },
    {
      id: "digital",
      title: "数字化升级",
      description: "整合企业系统与公共数字基础设施，交付自动化流程、数据报表和运营工具。",
      projects: [
        {
          id: "P-04",
          title: "国家地址系统（NAS）的技术与运营设计",
          shortTitle: "国家地址系统",
          purpose: "设计统一地址基础设施与治理框架，支持公共服务和物流应用。",
          paragraphs: ["物流、资源配置与公共治理依赖可用的地址信息。项目围绕国家地址系统设计总体架构，研究地址数据采集与视觉人工智能的应用方式。", "能力建设、培训工具与技术合规框架共同支撑系统运营，将技术设计与治理要求连接起来。应用希望为公共服务、物流规划和政策制定提供统一的地址基础。"],
          highlights: ["地址数据采集", "能力建设"],
          features: ["地址数据采集", "总体架构设计", "培训工具", "治理框架"],
          image: {"src": "/images/hil-site/projects/catalog/address-mapping-photo.webp", "width": 1536, "height": 1024, "alt": "国家地址系统（NAS）的技术与运营设计写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-16",
          title: "美赞臣营销管理系统",
          shortTitle: "营销管理",
          purpose: "连接受众分层、互动积分和数据分析，辅助企业组织营销活动。",
          paragraphs: ["企业开展营销时，需要理解不同受众的需求与偏好。系统提供个性化受众分层和定向触达，将互动积分机制连接到营销流程，组织用户参与。", "数据分析与报表呈现市场需求和用户反馈，为后续营销决策提供参考。项目把受众理解、互动和分析放在同一系统，帮助团队衔接营销运营工作。"],
          highlights: ["受众分层", "数据分析与报表"],
          features: ["受众分层", "定向触达", "互动积分", "分析报表"],
          image: {"src": "/images/hil-site/projects/catalog/marketing-dashboard-photo.webp", "width": 1536, "height": 1024, "alt": "美赞臣营销管理系统写实概念配图", "illustrative": true},
        },
        {
          id: "P-07-17",
          title: "定制仓库管理系统（WMS）",
          shortTitle: "仓库管理",
          purpose: "整合库存、订单与物流信息，通过实时监控和自动化辅助仓储运营。",
          paragraphs: ["人工记录与旧有系统容易让仓储工作出现重复操作和信息断点。定制仓库管理系统整合库存管理、订单处理与物流追踪，连接主要业务环节。", "实时数据监控与自动化操作共同支持日常管理，让团队能够在同一流程中跟进库存和订单。应用重点是减少手工处理步骤与人为差错，衔接仓储运营。"],
          highlights: ["库存管理", "实时数据监控"],
          features: ["库存管理", "订单处理", "物流追踪", "自动化操作"],
          image: {"src": "/images/hil-site/projects/catalog/warehouse-system-photo.webp", "width": 1536, "height": 1024, "alt": "定制仓库管理系统（WMS）写实概念配图", "illustrative": true},
        },
      ],
    },
  ],
  "en": [
    {
      id: "ai",
      title: "AI Solutions",
      description: "Deliver predictive models, knowledge bases, agents, and generative applications for health, public services, and industry.",
      projects: [
        {
          id: "P-03",
          title: "Integrated Digital Concierge with Real-Time Avatar Based on AI-RAG",
          shortTitle: "Digital concierge",
          purpose: "Make civic information easier to access through a conversational digital avatar.",
          paragraphs: ["Smart city and tourism services need accessible ways to answer visitor questions. This project connects a policy knowledge base with retrieval-augmented generation and a real-time digital avatar, allowing people to ask questions in natural conversation.", "Multilingual interaction helps different visitors access public-service information. Rendering and retrieval work together to support responses, creating a scalable touchpoint for civic enquiries and tourism reception."],
          highlights: ["policy knowledge base", "Multilingual interaction"],
          features: ["Policy retrieval", "Multilingual dialogue", "Real-time avatar"],
          image: {"src": "/images/hil-site/projects/catalog/civic-service-photo.webp", "width": 1536, "height": 1024, "alt": "Integrated Digital Concierge with Real-Time Avatar Based on AI-RAG — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-06",
          title: "Forecasting Energy Consumption for Predictive Maintenance",
          shortTitle: "Energy forecasting",
          purpose: "Use factory sensor data to inform energy forecasts and maintenance planning.",
          paragraphs: ["Reactive maintenance can leave manufacturing teams dealing with sudden failures and energy waste. The project cleans high-frequency sensor data and applies deep learning with adaptive dual distillation to examine energy changes and possible fault signals.", "Visual analytics dashboards make forecasts available to floor managers, supporting equipment assessment and maintenance planning. The aim is to help teams notice anomalies earlier and adjust schedules in light of operating conditions."],
          highlights: ["high-frequency sensor data", "Visual analytics dashboards"],
          features: ["Energy forecasting", "Anomaly identification", "Maintenance analytics"],
          image: {"src": "/images/hil-site/projects/catalog/energy-monitoring-photo.webp", "width": 1536, "height": 1024, "alt": "Forecasting Energy Consumption for Predictive Maintenance — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-01",
          title: "Early Prediction of NCDs from Imbalanced Sequence Data",
          shortTitle: "Early disease prediction",
          purpose: "Improve modeling of imbalanced medical sequences for early-warning research.",
          paragraphs: ["Long disease development periods and uneven sample distributions complicate early warning. The project extracts sequence structures from clinical datasets and studies dynamic data augmentation designed for those features.", "Cross-validation evaluates early-warning performance and explores ways to improve sensitivity to underrepresented samples. The research provides a methodological basis for risk identification and further medical-data analysis and validation."],
          highlights: ["dynamic data augmentation", "Cross-validation"],
          features: ["Sequence analysis", "Data augmentation", "Model evaluation"],
          image: {"src": "/images/hil-site/projects/catalog/clinical-research-photo.webp", "width": 1536, "height": 1024, "alt": "Early Prediction of NCDs from Imbalanced Sequence Data — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-02",
          title: "Facial Expression Recognition for Elderly Mental Health Monitoring",
          shortTitle: "Elderly emotion monitoring",
          purpose: "Combine non-contact expression analysis and conversation to support emotional monitoring.",
          paragraphs: ["Emotional changes can be difficult to observe continuously in ageing-in-place settings. The project builds an elderly facial-feature dataset and uses multimodal modeling to examine expressions and emotional transitions alongside an empathetic conversational agent.", "Non-contact monitoring and dialogue feedback provide emotional cues, with psychological alerts sent to caregivers. These signals help caregivers notice changes and inform further communication and care."],
          highlights: ["emotional transitions", "Non-contact monitoring"],
          features: ["Expression analysis", "Emotion modeling", "Caregiver alerts"],
          image: {"src": "/images/hil-site/projects/catalog/elder-care-photo.webp", "width": 1536, "height": 1024, "alt": "Facial Expression Recognition for Elderly Mental Health Monitoring — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-04",
          title: "Scam Surveillance Model Integrating Web Scraping and LLMs",
          shortTitle: "Scam monitoring",
          purpose: "Combine image forensics and language analysis to identify potential scam signals.",
          paragraphs: ["Online scams change quickly, and keywords alone may miss deceptive intent across images and text. The project collects multimodal samples and combines image forensics with semantic language analysis.", "A joint classifier examines different information formats to support surveillance and early warning. The application focuses on identifying suspicious signals in complex online content and providing more targeted input for further review."],
          highlights: ["image forensics", "joint classifier"],
          features: ["Multimodal collection", "Joint classification", "Scam alerts"],
          image: {"src": "/images/hil-site/projects/catalog/scam-analysis-photo.webp", "width": 1536, "height": 1024, "alt": "Scam Surveillance Model Integrating Web Scraping and LLMs — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-05",
          title: "DingTalk AI Office Assistant",
          shortTitle: "DingTalk office assistant",
          purpose: "Bring tasks, schedules, and meeting reminders into one everyday collaboration workflow.",
          paragraphs: ["Missed tasks and scheduling conflicts can interrupt team collaboration. Integrated with DingTalk, the assistant brings task management, scheduling, and meeting reminders into the same workspace to help employees follow up on commitments.", "Routine automation and action reminders connect otherwise scattered steps to collaborative workflows. Teams can organize work around existing schedules and reduce reliance on memory and repeated manual operations."],
          highlights: ["task management", "action reminders"],
          features: ["Task management", "Scheduling", "Meeting reminders"],
          image: {"src": "/images/hil-site/projects/catalog/office-assistant-photo.webp", "width": 1536, "height": 1024, "alt": "DingTalk AI Office Assistant — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-06",
          title: "AI Fitness Assistant",
          shortTitle: "Fitness assistant",
          purpose: "Use personal health information and exercise habits to guide fitness goals.",
          paragraphs: ["Different physical conditions and exercise habits make generic plans a poor fit for some users. The project brings together health and activity information to build user profiles and recommend fitness plans aligned with individual circumstances.", "Goal setting and execution feedback connect recommendations to users' actions, helping them follow their training plans. The application focuses on a more personalized exercise-guidance experience."],
          highlights: ["user profiles", "Goal setting"],
          features: ["Health information", "Fitness recommendations", "Goals and feedback"],
          image: {"src": "/images/hil-site/projects/catalog/fitness-coach-photo.webp", "width": 1536, "height": 1024, "alt": "AI Fitness Assistant — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-07",
          title: "AI Art Image Generation Platform",
          shortTitle: "Art image generation",
          purpose: "Help users express creative ideas through text descriptions and style choices.",
          paragraphs: ["Personalized art creation can require specialist tools. The platform provides text descriptions and style selection as inputs to an image-generation workflow, supporting different painting styles and subjects.", "Generated works can be displayed and discussed within the platform, connecting creation with interaction. Users can express ideas more directly and explore visual work through different styles."],
          highlights: ["text descriptions", "style selection"],
          features: ["Text input", "Style selection", "Artwork interaction"],
          image: {"src": "/images/hil-site/projects/catalog/art-creation-photo.webp", "width": 1536, "height": 1024, "alt": "AI Art Image Generation Platform — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-10",
          title: "TikTok AI Lead Generation and Sales Automation System",
          shortTitle: "Lead discovery and sales",
          purpose: "Connect analysis of short-video comments with lead management and follow-up.",
          paragraphs: ["Potential demand is scattered across video comments, making manual discovery and follow-up cumbersome. The project collects videos and comments, then applies intelligent analysis to identify potential leads within that content.", "Lead tracking and preset messages connect discovery to subsequent communication. The application organizes the steps of collection, analysis, and follow-up to support sales teams' everyday lead management and customer interaction."],
          highlights: ["potential leads", "Lead tracking"],
          features: ["Video and comment collection", "Lead analysis", "Follow-up management"],
          image: {"src": "/images/hil-site/projects/catalog/sales-workflow-photo.webp", "width": 1536, "height": 1024, "alt": "TikTok AI Lead Generation and Sales Automation System — photorealistic concept image", "illustrative": true},
        },
      ],
    },
    {
      id: "edge",
      title: "Edge Intelligence",
      description: "Deploy lightweight computer vision on devices with real-time recognition and integrated hardware and software.",
      projects: [
        {
          id: "P-05",
          title: "Smart Grocer: Edge AI Produce Recognition System",
          shortTitle: "Fresh-produce recognition",
          purpose: "Integrate lightweight vision into retail scales to identify fruit and vegetables.",
          paragraphs: ["Fresh-produce checkout often relies on manual identification and product-code entry. The project builds an image dataset verified by agricultural taxonomy experts and trains lightweight vision models suited to edge chips.", "Integration with connected weighing hardware enables real-time recognition on the device, linking identification with weighing. The application aims to reduce manual entry and make produce checkout and product handling smoother."],
          highlights: ["lightweight vision models", "real-time recognition"],
          features: ["Produce recognition", "On-device inference", "Scale integration"],
          image: {"src": "/images/hil-site/projects/catalog/produce-scale-photo.webp", "width": 1536, "height": 1024, "alt": "Smart Grocer: Edge AI Produce Recognition System — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-03",
          title: "Autonomous Drone Mapping with Wireless Charging for Agriculture 4.0",
          shortTitle: "Agricultural drone mapping",
          purpose: "Combine autonomous routes, wireless charging, and image stitching for plantation surveys.",
          paragraphs: ["Plantation inspections are constrained by manual effort and drone endurance, limiting data collection frequency. The project configures autonomous routes and wireless charging stations, then uses computer vision for field-image stitching.", "Edge mapping connects to cloud analytics to produce maps and indicators for agricultural management. The focus is on sustained aerial inspection that helps managers understand field conditions and spatial information."],
          highlights: ["wireless charging stations", "field-image stitching"],
          features: ["Autonomous routes", "Wireless charging", "Image stitching", "Agricultural mapping"],
          image: {"src": "/images/hil-site/projects/catalog/agriculture-drone-photo.webp", "width": 1536, "height": 1024, "alt": "Autonomous Drone Mapping with Wireless Charging for Agriculture 4.0 — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-08",
          title: "AI Facial Recognition Access Control System",
          shortTitle: "Face access control",
          purpose: "Connect facial identity checks with access control and security workflows.",
          paragraphs: ["Access management needs to connect identity checks with entry permissions. The project captures and compares facial identity information, feeding recognition results into access control and associated security-monitoring workflows.", "Verification and entry handling become parts of the same process, giving staff a more direct operational path. The application supports identity verification and entry management in settings that use facial recognition."],
          highlights: ["identity checks", "access control"],
          features: ["Face comparison", "Identity verification", "Access control"],
          image: {"src": "/images/hil-site/projects/catalog/access-control-photo.webp", "width": 1536, "height": 1024, "alt": "AI Facial Recognition Access Control System — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-09",
          title: "GTorque Game Guide Assistant",
          shortTitle: "Game guide assistant",
          purpose: "Interpret scenes and tasks in game images to offer relevant guidance.",
          paragraphs: ["Players may find it difficult to identify important scenes, tasks, or routes during a game. The assistant applies image recognition and computer vision to connect recognized content with relevant guidance.", "Scene understanding and game tips support players as they progress, reducing the need to switch between play and separate explanations. The project focuses on targeted help during the playing experience."],
          highlights: ["image recognition", "game tips"],
          features: ["Scene recognition", "Task association", "Game guidance"],
          image: {"src": "/images/hil-site/projects/catalog/game-guide-photo.webp", "width": 1536, "height": 1024, "alt": "GTorque Game Guide Assistant — photorealistic concept image", "illustrative": true},
        },
      ],
    },
    {
      id: "products",
      title: "Custom Digital Products",
      description: "Build websites, mobile apps, and industry platforms connecting transactions, recommendations, and user engagement.",
      projects: [
        {
          id: "P-07-11",
          title: "Merace Metaverse Gaming Platform",
          shortTitle: "Merace game platform",
          purpose: "Connect platform currency, game items, and cross-game asset management.",
          paragraphs: ["Game platforms involve different assets, including currency, characters, and items. Merace organizes purchase and use workflows across blockchain games, connecting multiple titles through a shared asset interface.", "Cross-game asset management and trading link players' needs across titles. The platform connects item purchases, asset viewing, and transactions into a continuous experience across its gaming content."],
          highlights: ["asset interface", "Cross-game asset management"],
          features: ["Platform currency", "Character and item purchases", "Cross-game assets"],
          image: {"src": "/images/hil-site/projects/catalog/what_right1.webp", "width": 479, "height": 460, "alt": "Merace Metaverse Gaming Platform showcase image", "illustrative": false},
        },
        {
          id: "P-07-12",
          title: "Intelligent Insurance Services and Online Claims Platform",
          shortTitle: "Insurance and claims",
          purpose: "Connect product enquiries, online insurance purchases, and claims applications.",
          paragraphs: ["Insurance customers need continuity between learning about products, purchasing coverage, obtaining advice, and making claims. The platform brings product and service information together with online purchasing and intelligent customer support.", "Online claims applications and status handling extend the service beyond purchase. The application helps users move between information, communication, and transactions through a connected web experience."],
          highlights: ["online purchasing", "Online claims applications"],
          features: ["Product enquiries", "Online purchasing", "Intelligent support", "Claims applications"],
          image: {"src": "/images/hil-site/projects/catalog/insurance-service-photo.webp", "width": 1536, "height": 1024, "alt": "Intelligent Insurance Services and Online Claims Platform — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-13",
          title: "AI Social Commerce App",
          shortTitle: "Social commerce",
          purpose: "Combine product discovery, shopping stories, and recommendations in a mobile experience.",
          paragraphs: ["Product discovery in social commerce is closely connected to conversation. The app combines retail and social interaction, allowing people to discover and buy products while sharing their shopping experiences.", "Friend recommendations and user interaction inform product recommendations and targeted marketing. The project connects conversation with shopping so users can discover relevant products through social engagement."],
          highlights: ["social interaction", "Friend recommendations"],
          features: ["Product discovery", "Purchasing", "Shopping stories", "Recommendations"],
          image: {"src": "/images/hil-site/projects/catalog/what_right3.webp", "width": 479, "height": 460, "alt": "AI Social Commerce App showcase image", "illustrative": false},
        },
        {
          id: "P-07-14",
          title: "O2O Intelligent Matching and Activity-based Social Platform",
          shortTitle: "Social activities",
          purpose: "Match people through shared interests and connect them with suitable activities.",
          paragraphs: ["People looking for like-minded friends also need convenient ways to find and join activities. The platform uses interest profiles and intelligent matching to connect people and events through a shared interaction space.", "Event creation, management, and participation form a connected workflow, with interaction feedback used to improve matching. The focus is on linking introductions with shared activities and ongoing social exchange."],
          highlights: ["intelligent matching", "interaction feedback"],
          features: ["Interest matching", "Event creation", "Event management", "Participation"],
          image: {"src": "/images/hil-site/projects/catalog/what_right4.webp", "width": 479, "height": 460, "alt": "O2O Intelligent Matching and Activity-based Social Platform showcase image", "illustrative": false},
        },
        {
          id: "P-07-15",
          title: "RiceUp Local Food Delivery Platform",
          shortTitle: "RiceUp food delivery",
          purpose: "Bring nearby food, recommendations, and reviews together for discovery and ordering.",
          paragraphs: ["Choosing local food delivery involves preferences, service options, and other customers' feedback. RiceUp aggregates nearby restaurants and delivery services, connecting discovery and ordering within the same platform.", "Personalized recommendations and user reviews support dining choices, while feedback helps improve subsequent discovery. Browsing, choosing, ordering, and reviewing are organized into a convenient local-food experience."],
          highlights: ["Personalized recommendations", "user reviews"],
          features: ["Nearby food discovery", "Delivery ordering", "Recommendations", "Reviews"],
          image: {"src": "/images/hil-site/projects/catalog/food-delivery-photo.webp", "width": 1536, "height": 1024, "alt": "RiceUp Local Food Delivery Platform — photorealistic concept image", "illustrative": true},
        },
      ],
    },
    {
      id: "digital",
      title: "Digital Transformation",
      description: "Integrate enterprise systems and public digital infrastructure with automated workflows, analytics, and operational tools.",
      projects: [
        {
          id: "P-04",
          title: "Technical and Operation Design for National Address Systems (NAS)",
          shortTitle: "National address system",
          purpose: "Design shared address infrastructure and governance for public and logistics services.",
          paragraphs: ["Logistics, resource allocation, and public governance depend on usable address information. The project designs the national address system architecture and explores address-data collection with visual AI applications.", "Capacity building, training tools, and technical compliance frameworks support operations and connect system design with governance. The aim is a shared address foundation for public services, logistics planning, and policymaking."],
          highlights: ["address-data collection", "Capacity building"],
          features: ["Address collection", "System architecture", "Training tools", "Governance framework"],
          image: {"src": "/images/hil-site/projects/catalog/address-mapping-photo.webp", "width": 1536, "height": 1024, "alt": "Technical and Operation Design for National Address Systems (NAS) — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-16",
          title: "Mead Johnson Marketing Management System",
          shortTitle: "Marketing management",
          purpose: "Connect audience segments, interaction points, and analytics for marketing operations.",
          paragraphs: ["Marketing teams need to understand the needs and preferences of different audiences. The system connects personalized audience segmentation and targeted outreach with interactive points allocation to organize participation.", "Analytics and reports present market demand and user feedback to inform subsequent decisions. The project brings audience understanding, interaction, and analysis into one operational system."],
          highlights: ["audience segmentation", "Analytics and reports"],
          features: ["Audience segmentation", "Targeted outreach", "Interaction points", "Analytics and reports"],
          image: {"src": "/images/hil-site/projects/catalog/marketing-dashboard-photo.webp", "width": 1536, "height": 1024, "alt": "Mead Johnson Marketing Management System — photorealistic concept image", "illustrative": true},
        },
        {
          id: "P-07-17",
          title: "Custom Warehouse Management System (WMS)",
          shortTitle: "Warehouse management",
          purpose: "Connect inventory, orders, and logistics through live monitoring and automated workflows.",
          paragraphs: ["Manual records and older systems can create repeated work and information gaps in warehouses. The customized system combines inventory management, order processing, and logistics tracking across the main operational steps.", "Real-time monitoring and automated operations help teams follow inventory and orders in one workflow. The application focuses on reducing manual handling and human error while connecting everyday warehouse operations."],
          highlights: ["inventory management", "Real-time monitoring"],
          features: ["Inventory management", "Order processing", "Logistics tracking", "Automated operations"],
          image: {"src": "/images/hil-site/projects/catalog/warehouse-system-photo.webp", "width": 1536, "height": 1024, "alt": "Custom Warehouse Management System (WMS) — photorealistic concept image", "illustrative": true},
        },
      ],
    },
  ],
};
