#!/usr/bin/env python3
"""Build language-aligned laboratory website reference artifacts.

This script is deliberately deterministic: the Chinese DOCX is the content
authority, and the existing English files are used only as translation
evidence. It never edits the four source artifacts in REF; it writes named
copies and a stable-number difference report.
"""

from __future__ import annotations

import copy
import html as html_lib
import re
from collections import defaultdict
from pathlib import Path
from typing import Iterable

from docx import Document
from docx.shared import RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.text.paragraph import Paragraph
from lxml import etree, html


ROOT = Path(__file__).resolve().parents[1]
REF = ROOT / "REF"
REPORT = ROOT / "docs" / "research" / "实验室官网语言对齐差异清单.md"

ZH_DOCX = REF / "实验室官网内容填写包 v4（中文版）.docx"
EN_DOCX = REF / "实验室官网内容填写包 v4（English）.docx"
ZH_HTML = REF / "实验室官网线框预览V4.html"
EN_HTML = REF / "实验室官网线框预览V4（English）.html"

OUT_ZH_DOCX = REF / "实验室官网内容填写包 v4（中文版·语言统一版）.docx"
OUT_EN_DOCX = REF / "实验室官网内容填写包 v4（English·Language-aligned）.docx"
OUT_ZH_HTML = REF / "实验室官网线框预览V4（中文版·语言统一版）.html"
OUT_EN_HTML = REF / "实验室官网线框预览V4（English·Language-aligned）.html"

HAN = re.compile(r"[\u3400-\u9fff]")
SECTION_RE = re.compile(r"\b([HRPAN TC]-\d{2})\b")


# Exact UI/instruction translations. Content prose that already exists in the
# English source is not regenerated by an LLM; only these deterministic labels
# and the six missing modules are authored here.
EN_MAP = {
    "字段": "Field",
    "内容（周俊杰博士）": "Content (Dr. Chaw Jun Kit)",
    "实验室中文名": "Lab name in Chinese",
    "填写经确认的正式全称。": "Enter the confirmed official full name.",
    "怡和实验室": "Harmonizing Intelligence Lab (HI Lab)",
    "实验室英文名": "Lab name in English",
    "填写经确认的正式英文全称。": "Enter the confirmed official English name.",
    "愿景标题": "Vision title",
    "用 8—20 字概括长期方向。": "Summarize the long-term direction in 8–20 characters.",
    "愿景说明": "Vision statement",
    "用 60—120 字说明核心关注点。": "Describe the core focus in 60–120 characters.",
    "补充(示例)": "Additional note (example)",
    "对主视觉的说明。": "Describe the primary visual.",
    "编号": "ID",
    "对应内容名称": "Related Content Name",
    "固定详情入口说明": "Fixed Detail Entry",
    "固定进入研究方向页（数字健康）": "Always links to the research-direction page (Digital Health).",
    "固定进入研究方向页（边缘人工智能）": "Always links to the research-direction page (Edge AI).",
    "固定进入研究方向页（多智能体系统）": "Always links to the research-direction page (Agent Systems).",
    "固定进入研究方向页 (Digital Health)": "Always links to the research-direction page (Digital Health).",
    "固定进入研究方向页 (Edge AI)": "Always links to the research-direction page (Edge AI).",
    "固定进入研究方向页 (Agent Systems)": "Always links to the research-direction page (Agent Systems).",
    "固定映射": "Fixed Mapping",
    "卡片规则": "Card rule",
    "只显示“名称 + 优势”，固定进入技术优势页。": "Display only “Name + Advantage”; fixed link to the Technology Advantages page.",
    "填写说明": "Instructions",
    "项目编号填写": "Project ID",
    "填写其中一个项目编号。": "Enter one project ID.",
    "展示规则": "Display rule",
    "固定读取单位名称和标识（Advantech）": "Always reads the organization name and logo (Advantech).",
    "固定读取单位名称和标识（HILTI）": "Always reads the organization name and logo (HILTI).",
    "固定读取单位名称和标识（Tokio Marine）": "Always reads the organization name and logo (Tokio Marine).",
    "固定读取单位名称和标识（Xiamen University Malaysia）": "Always reads the organization name and logo (Xiamen University Malaysia).",
    "固定读取单位名称和标识（Leeds Beckett University）": "Always reads the organization name and logo (Leeds Beckett University).",
    "固定读取单位名称和标识（Three-Opp）": "Always reads the organization name and logo (Three-Opp).",
    "固定读取单位名称和 Logo (Advantech)": "Always reads the organization name and logo (Advantech).",
    "固定读取单位名称和 Logo (HILTI)": "Always reads the organization name and logo (HILTI).",
    "固定读取单位名称和 Logo (Tokio Marine/Dynafront)": "Always reads the organization name and logo (Tokio Marine/Dynafront).",
    "固定读取单位名称和 Logo (Xiamen University Malaysia)": "Always reads the organization name and logo (Xiamen University Malaysia).",
    "固定读取单位名称和 Logo (Leeds Beckett University)": "Always reads the organization name and logo (Leeds Beckett University).",
    "固定读取单位名称和 Logo (Three-Opp)": "Always reads the organization name and logo (Three-Opp).",
    "固定进入团队页。": "Always links to the team page.",
    "课题负责人（PI）": "Principal Investigator (PI)",
    "固定详情入口说明": "Fixed detail-entry rule",
    "首页排序第 1 的合作形式": "Collaboration format ranked first on the home page",
    "首页排序第 2 的合作形式": "Collaboration format ranked second on the home page",
    "首页排序第 3 的合作形式": "Collaboration format ranked third on the home page",
    "固定进入联系合作页（产业技术转移）": "Always links to the contact page (Industrial Tech Transfer).",
    "固定进入联系合作页（联合学术研究）": "Always links to the contact page (Joint Academic Research).",
    "固定进入联系合作页（研究生人才招募）": "Always links to the contact page (Postgraduate Talent Recruitment).",
    "固定进入联系合作页 (Industrial Tech Transfer)": "Always links to the contact page (Industrial Tech Transfer).",
    "固定进入联系合作页 (Joint Academic Research)": "Always links to the contact page (Joint Academic Research).",
    "固定进入联系合作页 (Talent Recruitment)": "Always links to the contact page (Talent Recruitment).",
    "填写项": "Entry",
    "填写说明/建议长度": "Instructions / Suggested Length",
    "Content（周俊杰博士）": "Content (Dr. Chaw Jun Kit)",
    "Content": "Content",
    "页面标题": "Page Title",
    "填写研究方向页的正式标题。": "Enter the official title of the research-direction page.",
    "首页简述": "Homepage Summary",
    "供 H-02 只读引用，概括方向。": "Read-only summary cited by H-02.",
    "内页导语": "Inner-Page Introduction",
    "概括实验室研究什么。": "Summarize what the lab researches.",
    "名称": "Name",
    "填写确认后的中英文名。": "Enter the confirmed Chinese and English names.",
    "一句话定义": "One-Sentence Definition",
    "直接说明该方向研究什么。": "State directly what this direction studies.",
    "关注问题": "Key Questions",
    "列出长期关注的核心问题。": "List the core long-term questions.",
    "主要研究内容": "Main Research Content",
    "填写研究对象、任务等。": "Enter the research objects, tasks, and related details.",
    "应用场景": "Application Scenarios",
    "列出可明确说明的应用环境。": "List application environments that can be described clearly.",
    "代表项目": "Representative Projects",
    "填写已确认的 P 编号。": "Enter confirmed P IDs.",
    "补充": "Additional Notes",
    "需要注意或补充的事项。": "Important notes or additions.",
    "共同问题": "Shared Problem",
    "说明共同面向的上位问题。": "Describe the higher-level problem shared by all pillars.",
    "各自边界": "Individual Boundaries",
    "分别说明三个方向的边界。": "Describe the boundary of each of the three directions.",
    "连接方式": "Connection Method",
    "说明三者的连接复用关系。": "Explain how the three pillars connect and reuse one another.",
    "关系视觉": "Relationship Visual",
    "填写关系图说明。": "Describe the relationship diagram.",
    "场景与项目对应": "Scenarios & Project Mapping",
    "按“应用场景名称：P 编号”填写。": "Use the format “scenario name: P ID”.",
    "不强行归入三大研究支柱。": "Do not force this into one of the three research pillars.",
    "项目名称": "Project Name",
    "填写正式项目名称。": "Enter the official project name.",
    "S 情境": "S — Situation",
    "说明场景、现状与约束。": "Describe the setting, current state, and constraints.",
    "T 任务": "T — Task",
    "说明目标与团队责任。": "Describe the objective and the team’s responsibility.",
    "A 行动": "A — Action",
    "填写具体行动。": "Enter the concrete actions.",
    "R 结果": "R — Result",
    "填写公开结果。": "Enter the public result.",
    "填写公开结果；自述指标须注明待核验。": "Enter the public result; self-reported metrics must be marked for verification.",
    "项目图片": "Project Image",
    "仅登记素材路径、用途、替代文本与版权状态；不嵌入图片。": "Record only the asset path, use, alt text, and copyright status; do not embed the image.",
    "资料属性": "Source / Evidence Metadata",
    "注明来源、归属和证据边界。": "State the source, attribution, and evidence boundary.",
    "固定项": "Fixed Item",
    "固定内容": "Fixed Content",
    "标题": "Title",
    "欢迎项目合作 (Welcome Collaboration)": "Welcome Collaboration",
    "说明": "Description",
    "按钮": "Button",
    "目标": "Target",
    "联系合作页 (Link to Contact Page)": "Contact page",
    "首页与伙伴页共用导语": "Shared Homepage and Partners-Page Intro",
    "一句话说明收录哪些单位。": "Briefly state which organizations are included.",
    "条目编号": "Entry ID",
    "单位名称": "Organization Name",
    "Logo文件或位置说明": "Logo File or Location",
    "Logo是否允许公开使用": "Logo Public-Use Permission",
    "单位名称": "Organization name",
    "填写团队页正式标题。": "Enter the official team-page title.",
    "概括团队构成。": "Summarize the team composition.",
    "概括团队定位。": "Summarize the team’s role.",
    "姓名": "Name",
    "中英文姓名及展示顺序。": "Chinese and English names and display order.",
    "职称/角色": "Title / Role",
    "正式职称及角色。": "Official title and role.",
    "单位": "Affiliation",
    "正式单位机构。": "Official institutional affiliation.",
    "研究兴趣": "Research Interests",
    "研究兴趣关键词。": "Research-interest keywords.",
    "短简介": "Short Bio",
    "教育或工作背景及职责。": "Educational or professional background and responsibilities.",
    "研究方向": "Research Areas",
    "引用已确认的 R 编号。": "Cite confirmed R IDs.",
    "代表项目/成果": "Representative Projects / Outputs",
    "引用代表项目或成果编号。": "Cite representative project or output IDs.",
    "个人链接": "Personal Link",
    "个人或学术主页。": "Personal or academic homepage.",
    "照片": "Photo",
    "照片说明。": "Photo description.",
    "想要补充的说明。": "Additional information.",
    "类型": "Type",
    "类型 (Type)": "Type",
    "数量": "Count",
    "公开方式": "Publication Status",
    "补充说明": "Additional Notes",
    "补充 (Notes)": "Additional Notes",
    "合作对象": "Collaboration Target",
    "合作对象 (Target)": "Collaboration Target",
    "合作方向与关联编号": "Collaboration Direction & Related IDs",
    "合作方向与关联编号 (Direction)": "Collaboration Direction & Related IDs",
    "适用边界与补充": "Scope & Notes",
    "适用边界与补充 (Notes)": "Scope & Notes",
    "合作形式": "Collaboration Format",
    "合作形式 (Format)": "Collaboration Format",
    "适合对象/场景": "Suitable Target / Scenario",
    "适合对象/场景 (Target/Scenario)": "Suitable Target / Scenario",
    "投入、流程与补充": "Investment, Process & Notes",
    "投入、流程与补充 (Investment/Process)": "Investment, Process & Notes",
    "招募对象": "Recruitment Target",
    "填写招募的学生类型。": "Enter the student type being recruited.",
    "方向": "Direction",
    "填写开放的研究方向。": "Enter the open research direction.",
    "申请方式": "Application Method",
    "填写申请材料及要求。": "Enter the required application materials.",
    "当前状态": "Current Status",
    "填写招募状态。": "Enter the recruitment status.",
    "联系人": "Contact Person",
    "联系人姓名。": "Contact person’s name.",
    "邮箱": "Email",
    "正式联系邮箱。": "Official contact email.",
    "地点": "Location",
    "获准公开的地址。": "Approved public address.",
    "社媒/预约": "Social / Booking",
    "社交媒体或学术主页。": "Social-media or academic homepage.",
    "联系时提供什么": "What to Provide When Contacting",
    "首次沟通应提供的内容。": "What to provide in the initial communication.",
    "可响应哪些事项": "Matters We Respond To",
    "明确可处理的咨询。": "Specify the inquiries we can handle.",
    "预计回复说明": "Expected Response",
    "预计回复时间。": "Expected response time.",
    "实验室官网｜English v3 内容线框预览": "Laboratory Website | English v3 Content Wireframe Preview",
    "跳到主要内容": "Skip to main content",
    "页面预览导航": "Page preview navigation",
    "线框图例": "Wireframe legend",
    "虚线框：素材与重复条目边界": "Dashed box: asset and repeated-entry boundary",
    "红字": "Red text",
    "：与内容填写包一致的长度提示": ": length guidance matching the content package",
    "v3-contract-1 · 已填充 · 单文件离线 · 7页 · 打印全部展开": "v3-contract-2 · populated · single-file offline · 7 pages · print expands all",
    "v3 字段合同：页面编号、字段名与首页引用均为固定结构": "v3 field contract: page IDs, field names, and home-page references are fixed",
    "七段式研究蓝图：仅呈现简述、亮点与对应子页引用。": "Seven-part research blueprint: summaries, highlights, and linked subpages only.",
    "愿景标题 8—20 字；愿景说明 60—120 字": "Vision title 8–20 characters; vision statement 60–120 characters",
    "愿景": "Vision",
    "主视觉创意说明": "Primary visual concept",
    "素材文件、版权与替代文本：待提供": "Asset file, copyright, and alt text: to be provided",
    "愿景视觉": "Vision visual",
    "与愿景说明对应的图片或视频": "Image or video corresponding to the vision statement",
    "查看研究方向": "View research directions",
    "固定引用 A-01 至 A-03，仅呈现名称与优势。": "Fixed references A-01 to A-03; show names and advantages only.",
    "查看技术优势": "View technology advantages",
    "已选择三个互不重复的项目编号：P-03、P-04、P-05；标题读取对应项目的“项目名称”，摘要读取“R 结果”。": "Three distinct project IDs are selected: P-07-06, P-07-08, and P-07-05; titles read the corresponding project names and summaries read the R results.",
    "查看项目详情": "View project details",
    "允许公开使用": "Approved for public use",
    "查看合作伙伴": "View partners",
    "查看团队详情": "View team details",
    "查看合作方式": "View collaboration options",
    "研究什么、方向关系，以及场景与项目如何对应。": "What the lab studies, how directions relate, and how scenarios map to projects.",
    "素材区域：研究方向总览图片或视频": "Asset area: research-direction overview image or video",
    "素材编号、构图重点、版权与替代文本：待提供": "Asset ID, composition focus, copyright, and alt text: to be provided",
    "固定进入首页 H-02-01｜首页排序 1": "Fixed home-page entry H-02-01 | home-page order 1",
    "素材区域：HEALTH 方向图片或视频": "Asset area: HEALTH direction image or video",
    "固定进入首页 H-02-02｜首页排序 2": "Fixed home-page entry H-02-02 | home-page order 2",
    "素材区域：EDGE-AI 方向图片或视频": "Asset area: EDGE-AI direction image or video",
    "固定进入首页 H-02-03｜首页排序 3": "Fixed home-page entry H-02-03 | home-page order 3",
    "素材区域：AGENT 方向图片或视频": "Asset area: AGENT direction image or video",
    "共同问题建议 50—100 字；各自边界建议每个方向 30—60 字；连接方式建议 80—150 字": "Suggested length: shared problem 50–100 characters; each boundary 30–60; connection model 80–150",
    "三方向关系": "Three-direction relationship",
    "素材区域：三个研究方向关系图或视频": "Asset area: relationship diagram or video for the three directions",
    "素材编号、版权与替代文本：待提供": "Asset ID, copyright, and alt text: to be provided",
    "按“应用场景名称：P 编号”填写，不重复项目正文": "Use “scenario name: P ID”; do not repeat project descriptions",
    "跨方向项目": "Cross-direction projects",
    "素材区域：项目总览图片或视频": "Asset area: project-overview image or video",
    "固定合作邀请｜按钮目标 Contact": "Fixed collaboration invitation | button target: Contact",
    "固定进入 H-03-01": "Fixed entry H-03-01",
    "固定进入 H-03-02": "Fixed entry H-03-02",
    "固定进入 H-03-03": "Fixed entry H-03-03",
    "前沿技术储备｜暂不进入首页 H-03": "Frontier technology reserve | not shown on home-page H-03",
    "仅展示一句导语与获准公开的伙伴 Logo 墙。": "Show only one introduction and the approved partner-logo wall.",
    "首页与合作伙伴页使用同一句 30—60 字导语": "The home and partner pages use the same 30–60-character introduction",
    "两页共用导语": "Shared introduction",
    "两页共用导语｜30—60字": "Shared introduction | 30–60 characters",
    "固定 12 个 Logo 槽｜不足12项的槽位填暂无｜每槽四字段": "Fixed 12 logo slots | fill unused slots with “Not provided” | four fields per slot",
    "Logo墙清单": "Logo wall list",
    "伙伴 Logo 字段列表": "Partner-logo field list",
    "团队导语、PI、团队构成与9个成员模板/槽位。": "Team introduction, PI, team composition, and nine member templates/slots.",
    "研究兴趣填写 3—6 个关键词；短简介建议 100—180 字；代表项目/成果建议 3—6 项": "Enter 3–6 research-interest keywords; suggested short biography 100–180 characters; 3–6 representative projects/outputs",
    "周俊杰": "Dr. Chaw Jun Kit",
    "周俊杰 Dr. Chaw Jun Kit": "Dr. Chaw Jun Kit",
    "周俊杰博士": "Dr. Chaw Jun Kit",
    "王鸿清": "Dr. Jeff Wang",
    "王鸿清 Dr. Jeff Wang": "Dr. Jeff Wang",
    "DOCX 内嵌照片 · 405 × 465 pixels": "DOCX embedded photo · 405 × 465 pixels",
    "版权状态：待确认": "Copyright status: To be confirmed",
    "只保留实际存在的成员类型": "Keep only member types that actually exist",
    "团队构成": "Team composition",
    "补充：": "Notes: ",
    "数量 / 公开方式：": "Count / publication status: ",
    "固定9个成员模板/槽位｜每槽三字段": "Fixed nine member templates/slots | three fields per slot",
    "成员": "Members",
    "合作对象、合作形式、学生申请、联系方式与响应范围。": "Collaboration targets, formats, student applications, contact details, and response scope.",
    "只列对象、方向名称与适用边界，可引用已确认的 R/P/A 编号": "List only targets, direction names, and boundaries; confirmed R/P/A IDs may be cited",
    "合作对象及方向": "Collaboration targets and directions",
    "合作形式": "Collaboration formats",
    "固定三项合作形式｜与 H-07-01 至 H-07-03 逐一对应": "Fixed three collaboration formats | one-to-one mapping to H-07-01 through H-07-03",
    "招募信息固定四字段": "Recruitment information has four fixed fields",
    "学生申请": "Student applications",
    "只展示获准公开并已确认的联系信息": "Show only approved and confirmed public contact information",
    "联系方式": "Contact information",
    "不制作未经确认的联系表单": "Do not create an unconfirmed contact form",
    "联系准备与响应范围": "Contact preparation and response scope",
    "联系时提供什么": "What to provide when contacting",
    "可响应哪些事项": "Supported inquiries",
    "素材须包含素材编号、用途、版权和替代文本": "Assets must include an ID, use, copyright status, and alt text",
    "视觉": "Visuals",
    "素材区域：联系合作页图片或视频": "Asset area: contact/collaboration-page image or video",
    "联系页主视觉": "Contact-page primary visual",
    "素材区域：补充视觉": "Asset area: supplementary visual",
    "打印预览按文档流连续展开全部 7 个页面。": "Print preview expands all seven pages continuously in document flow.",
    "合作者": "Collaborator",
}

# The Chinese source uses a few variants of the same fixed labels. Keep these
# short technical/display variants separate from prose so a replacement cannot
# accidentally change a source path or an official name.
EN_MAP.update(
    {
        "HEALTH 对应": "HEALTH mapping",
        "EDGE-AI 对应": "EDGE-AI mapping",
        "AGENT 对应": "AGENT mapping",
        "补充产业应用": "Additional Industry Applications",
        "R-06 场景与项目对应": "R-06 Scenarios & Project Mapping",
        "A-04 跨模型 Skill 编译与运行治理": "A-04 Cross-Model Skill Compilation & Runtime Governance",
        "A-05 用户可控的分层 AI 记忆": "A-05 User-Controlled Layered AI Memory",
        "A-06 效用—多样性训练数据选择": "A-06 Utility–Diversity Training Data Selection",
        "A-07 设备端 Agent 与硬件协同": "A-07 On-Device Agents & Hardware Co-Design",
        "A-08 可验证反馈驱动的持续学习": "A-08 Verifiable Feedback-Driven Continual Learning",
        "跨模型 Skill 编译与运行治理": "Cross-Model Skill Compilation & Runtime Governance",
        "用户可控的分层 AI 记忆": "User-Controlled Layered AI Memory",
        "效用—多样性训练数据选择": "Utility–Diversity Training Data Selection",
        "设备端 Agent 与硬件协同": "On-Device Agents & Hardware Co-Design",
        "可验证反馈驱动的持续学习": "Verifiable Feedback-Driven Continual Learning",
        "什么样的优势": "Advantage",
        "方法": "Method",
        "优势": "Advantage",
        "跨方向项目": "Cross-direction projects",
        "素材编号、内容说明、版权与替代文本：待提供": "Asset ID, content description, copyright, and alt text: to be provided",
        # Values found in the existing English DOCX after the first M1 pass.
        # These are exact cells/instructions, not broad substring rewrites.
        "填写项目页的正式标题。": "Enter the official title of the Projects page.",
        "概括项目价值，不展开。": "Summarize project value without elaboration.",
        "概括实验室通过项目解决什么问题。": "Summarize what problems the lab addresses through projects.",
        "填写技术优势名称。": "Enter the technology advantage name.",
        "说明关键方法与适用条件。": "Describe the key method and applicable conditions.",
        "说明具体优势与适用边界。": "Describe the specific advantage and applicability boundaries.",
        "身份": "Status",
        "一句话简介": "One-Sentence Bio",
        "填写联系合作页正式标题。": "Enter the official title of the Contact page.",
        "概括适合联系的合作事项。": "Summarize suitable reasons to contact the lab.",
        "说明欢迎哪些合作咨询。": "Describe which collaboration inquiries are welcome.",
        "周俊杰 Dr. Chaw Jun Kit": "Dr. Chaw Jun Kit",
        "HEALTH（数字健康与医学影像分析）": "HEALTH (Digital Health & Medical Image Analytics)",
        "EDGE-AI（边缘智能与端侧视觉）": "EDGE-AI (Edge Intelligence & On-Device Vision)",
        "AGENT（多智能体系统与自然语言处理）": "AGENT (Multi-Agent Systems & NLP)",
        "按“应用场景名称：P 编号”填写，不重复项目正文": "Use “scenario name: P ID”; do not repeat project descriptions",
        "职称或角色": "Title or Role",
        "内容（P-03）": "Content (P-03)",
        "内容（P-04）": "Content (P-04)",
        "内容（P-05）": "Content (P-05)",
        "内容（P-06）": "Content (P-06)",
        "内容（P-07）": "Content (P-07)",
        "内容（P-07-01）": "Content (P-07-01)",
        "内容（P-07-02）": "Content (P-07-02)",
        "内容（P-07-03）": "Content (P-07-03)",
        "内容（P-07-04）": "Content (P-07-04)",
        "内容（P-07-05）": "Content (P-07-05)",
        "内容（P-07-06）": "Content (P-07-06)",
        "内容（P-07-07）": "Content (P-07-07)",
        "内容（P-07-08）": "Content (P-07-08)",
        "内容（P-07-09）": "Content (P-07-09)",
        "内容（P-07-10）": "Content (P-07-10)",
        "内容（P-07-11）": "Content (P-07-11)",
        "内容（P-07-12）": "Content (P-07-12)",
        "内容（P-07-13）": "Content (P-07-13)",
        "内容（P-07-14）": "Content (P-07-14)",
        "内容（P-07-15）": "Content (P-07-15)",
        "内容（P-07-16）": "Content (P-07-16)",
        "内容（P-07-17）": "Content (P-07-17)",
        "内容（T-04-01）": "Content (T-04-01)",
        "内容（T-04-02）": "Content (T-04-02)",
        "内容（T-04-03）": "Content (T-04-03)",
        "内容（T-04-04）": "Content (T-04-04)",
        "内容（T-04-05）": "Content (T-04-05)",
        "内容（T-04-06）": "Content (T-04-06)",
        "内容（T-04-07）": "Content (T-04-07)",
        "内容（T-04-08）": "Content (T-04-08)",
        "内容（T-04-09）": "Content (T-04-09)",
        "内容（T-04-10）": "Content (T-04-10)",
        "内容（T-04-11）": "Content (T-04-11)",
        "内容（T-04-12）": "Content (T-04-12)",
        "内容（T-04-13）": "Content (T-04-13)",
        "内容（T-04-14）": "Content (T-04-14)",
        "内容（T-04-15）": "Content (T-04-15)",
        "内容（T-04-16）": "Content (T-04-16)",
        "内容（T-04-17）": "Content (T-04-17)",
        "内容（T-04-18）": "Content (T-04-18)",
        "内容（T-04-19）": "Content (T-04-19)",
        "内容（T-04-20）": "Content (T-04-20)",
        "内容（T-04-21）": "Content (T-04-21)",
        "内容（T-04-22）": "Content (T-04-22)",
        "内容（T-04-23）": "Content (T-04-23)",
        "内容（T-04-24）": "Content (T-04-24)",
        "内容（T-04-25）": "Content (T-04-25)",
        "内容（T-04-26）": "Content (T-04-26)",
        "内容（T-04-27）": "Content (T-04-27)",
        "内容（T-04-28）": "Content (T-04-28)",
        "内容（T-04-29）": "Content (T-04-29)",
        "内容（T-04-30）": "Content (T-04-30)",
        "内容（T-04-31）": "Content (T-04-31)",
        "内容（T-04-32）": "Content (T-04-32)",
        "内容（T-04-33）": "Content (T-04-33)",
        "内容（T-04-34）": "Content (T-04-34)",
        "内容（T-04-35）": "Content (T-04-35)",
        "内容（T-04-36）": "Content (T-04-36)",
        "内容（T-04-37）": "Content (T-04-37)",
        "内容（T-04-38）": "Content (T-04-38)",
        "内容（T-04-39）": "Content (T-04-39)",
        "内容（T-04-40）": "Content (T-04-40)",
        "内容（T-04-41）": "Content (T-04-41)",
        "内容（T-04-42）": "Content (T-04-42)",
        "内容（T-04-43）": "Content (T-04-43)",
        "内容（T-04-44）": "Content (T-04-44)",
        "内容（T-04-45）": "Content (T-04-45)",
        "内容（T-04-46）": "Content (T-04-46)",
        "内容（T-04-47）": "Content (T-04-47)",
        "内容（T-04-48）": "Content (T-04-48)",
        "内容（T-04-49）": "Content (T-04-49)",
        "内容（T-04-50）": "Content (T-04-50)",
        "内容（T-04-51）": "Content (T-04-51)",
        "内容（T-04-52）": "Content (T-04-52)",
        "内容（T-04-53）": "Content (T-04-53)",
        "内容（T-04-54）": "Content (T-04-54)",
        "内容（T-04-55）": "Content (T-04-55)",
        "内容（T-04-56）": "Content (T-04-56)",
        "内容（T-04-57）": "Content (T-04-57)",
        "内容（T-04-58）": "Content (T-04-58)",
        "内容（T-04-59）": "Content (T-04-59)",
        "内容（T-04-60）": "Content (T-04-60)",
        "内容（T-04-61）": "Content (T-04-61)",
        "内容（T-04-62）": "Content (T-04-62)",
        "内容（T-04-63）": "Content (T-04-63)",
        "内容（T-04-64）": "Content (T-04-64)",
        "内容（T-04-65）": "Content (T-04-65)",
        "内容（T-04-66）": "Content (T-04-66)",
        "内容（T-04-67）": "Content (T-04-67)",
        "内容（T-04-68）": "Content (T-04-68)",
        "内容（T-04-69）": "Content (T-04-69)",
        "内容（T-04-70）": "Content (T-04-70)",
        "内容（T-04-71）": "Content (T-04-71)",
        "内容（T-04-72）": "Content (T-04-72)",
        "内容（T-04-73）": "Content (T-04-73)",
        "内容（T-04-74）": "Content (T-04-74)",
        "内容（T-04-75）": "Content (T-04-75)",
        "内容（T-04-76）": "Content (T-04-76)",
        "内容（T-04-77）": "Content (T-04-77)",
        "内容（T-04-78）": "Content (T-04-78)",
        "内容（T-04-79）": "Content (T-04-79)",
        "内容（T-04-80）": "Content (T-04-80)",
        "内容（T-04-81）": "Content (T-04-81)",
        "内容（T-04-82）": "Content (T-04-82)",
        "内容（T-04-83）": "Content (T-04-83)",
        "内容（T-04-84）": "Content (T-04-84)",
        "内容（T-04-85）": "Content (T-04-85)",
        "内容（T-04-86）": "Content (T-04-86)",
        "内容（T-04-87）": "Content (T-04-87)",
        "内容（T-04-88）": "Content (T-04-88)",
        "内容（T-04-89）": "Content (T-04-89)",
        "内容（T-04-90）": "Content (T-04-90)",
        "内容（T-04-91）": "Content (T-04-91)",
        "内容（T-04-92）": "Content (T-04-92)",
        "内容（T-04-93）": "Content (T-04-93)",
        "内容（T-04-94）": "Content (T-04-94)",
        "内容（T-04-95）": "Content (T-04-95)",
        "内容（T-04-96）": "Content (T-04-96)",
        "内容（T-04-97）": "Content (T-04-97)",
        "内容（T-04-98）": "Content (T-04-98)",
        "内容（T-04-99）": "Content (T-04-99)",
        # HTML shell labels and exact status/asset values.
        "首页": "Home",
        "项目": "Projects",
        "技术优势": "Technology Advantages",
        "合作伙伴": "Partners",
        "团队": "Team",
        "联系合作": "Contact",
        "首页简述与内页导语分开填写，首页只引用简述": "Fill the homepage summary and inner-page introduction separately; the homepage uses the summary only.",
        "研究方向 Research": "Research Directions",
        "研究方向总览": "Research Directions Overview",
        "技术优势 Technology Advantages": "Technology Advantages",
        "项目 Projects": "Projects",
        "合作伙伴 Partners": "Partners",
        "团队 Team": "Team",
        "联系合作 Contact": "Contact",
        "首页展示": "Homepage Display",
        "排序": "Sort",
        "要求：": "Requirement: ",
        "说明：": "Note: ",
        "投入：": "Investment: ",
        "流程：": "Process: ",
        "邮件主题：": "Subject Line: ",
        "联系方式": "Contact Information",
        "图片或视频": "Image or video",
        "素材区域": "Asset area",
        "素材编号、内容说明、版权与替代文本": "Asset ID, description, copyright, and alt text",
        "素材编号、构图重点、版权与替代文本": "Asset ID, composition focus, copyright, and alt text",
        "资料属性": "Source / Evidence Metadata",
        "适用边界或前提": "Scope & Prerequisites",
        "版权状态：": "Copyright status: ",
        "待提供": "To be provided",
        "待确认": "To be confirmed",
        "待定": "TBD",
        "暂无": "Not provided",
        "未提供": "Not provided",
        "公开": "Public",
        "长期开放招募（正式入学时间以 UKM 校历为准）。": "Long-term Open Recruitment (Official intakes follow the UKM academic calendar).",
        "访问 UKMsarjana 主页": "Visit UKMsarjana Profile",
        "我们回复以下咨询：": "We Respond To: ",
        "我们不回复以下咨询：": "We Do Not Respond To: ",
        "视觉": "Visuals",
        "打印预览按文档流连续展开全部 7 个页面。": "Print preview expands all seven pages continuously in document flow.",
        "技术优势页": "Technology Advantages page",
        "项目页": "Projects page",
        "项目总览": "Project overview",
        "研究方向页": "Research Directions page",
        "团队页": "Team page",
        "联系合作页": "Contact page",
        "合作方向 / 关联内容编号": "Collaboration Direction & Related IDs",
        "双方预期投入：": "Mutual investment: ",
        "确认流程：": "Confirmation process: ",
        "只读编号": "Read-only ID",
        "素材编号、用途、版权与替代文本：待提供": "Asset ID, use, copyright, and alt text: To be provided",
        "页面标题｜6—14字": "Page title | 6–14 characters",
        "首页简述｜40—70字": "Homepage summary | 40–70 characters",
        "内页导语｜100—180字": "Inner-page introduction | 100–180 characters",
        "页面标题｜4—12字": "Page title | 4–12 characters",
        "两页共用导语｜30—60字": "Shared introduction for both pages | 30–60 characters",
    }
)

MISSING_EN = {
    "R-06": {
        "heading": "R-06 Scenarios & Project Mapping",
        "rows": [
            ("Field", "Instructions / suggested length", "Content"),
            ("HEALTH mapping", "Use the format “scenario name: P ID”; do not repeat project descriptions.", "Early Prediction of NCDs: P-07-01; Elderly Mental Health Monitoring: P-07-02; Personalized Fitness Guidance: P-07-06."),
            ("EDGE-AI mapping", "Use the format “scenario name: P ID”; do not repeat project descriptions.", "Smart Grocer Produce Recognition: P-05; Agriculture 4.0 Drone Mapping: P-07-03; Facial Recognition Access Control: P-07-08; Game Visual Guide: P-07-09."),
            ("AGENT mapping", "Use the format “scenario name: P ID”; do not repeat project descriptions.", "AI-RAG Digital Concierge: P-03; National Address System: P-04; Scam Monitoring: P-07-04; DingTalk Office Assistant: P-07-05; TikTok Lead Generation & Sales: P-07-10."),
            ("Additional industry applications", "Do not force this into one of the three research pillars.", "AI Art Image Generation Platform: P-07-07; Merace Metaverse Gaming Platform: P-07-11; Intelligent Insurance Services and Online Claims Platform: P-07-12; AI Social Commerce App: P-07-13; O2O Intelligent Matching and Activity-based Social Platform: P-07-14; RiceUp Local Food Delivery Platform: P-07-15; Mead Johnson Marketing Management System: P-07-16; Custom Warehouse Management System (WMS): P-07-17."),
        ],
    },
    "A-04": {
        "heading": "A-04 Cross-Model Skill Compilation & Runtime Governance",
        "rows": [
            ("Field", "Instructions / suggested length", "Content"),
            ("Name", "Enter the technology-advantage name.", "Cross-Model Skill Compilation & Runtime Governance"),
            ("Method", "Describe the key method and applicable conditions.", "We treat Skills as compilable natural-language programs. Based on the capability profiles of models, Agent frameworks, and host environments, we perform ahead-of-time (AOT) adaptation, dependency binding, concurrent workflow orchestration, and runtime feedback optimization, while retaining version rollback capability."),
            ("Advantage", "Describe the concrete advantage and its boundary.", "Reduces repetitive rewrites, blind retries, and environment failures when migrating Skills across models and frameworks, making task success rates, latency, token consumption, and failure causes easier to track and optimize."),
        ],
    },
    "A-05": {
        "heading": "A-05 User-Controlled Layered AI Memory",
        "rows": [
            ("Field", "Instructions / suggested length", "Content"),
            ("Name", "Enter the technology-advantage name.", "User-Controlled Layered AI Memory"),
            ("Method", "Describe the key method and applicable conditions.", "We separate conversational working memory, structured long-term memory, and the proactive suggestion layer. Rule-based routing, explicit associations, source records, expiry reviews, and deletion mechanisms are combined to manage the lifecycle of memory storage, retrieval, and removal."),
            ("Advantage", "Describe the concrete advantage and its boundary.", "Reduces the need for users to repeat information while keeping sources traceable, content editable, permissions controllable, and expired memories removable. If long-term memory is unavailable, the system can still fall back to a standard single-session conversation."),
        ],
    },
    "A-06": {
        "heading": "A-06 Utility–Diversity Training Data Selection",
        "rows": [
            ("Field", "Instructions / suggested length", "Content"),
            ("Name", "Enter the technology-advantage name.", "Utility–Diversity Training Data Selection"),
            ("Method", "Describe the key method and applicable conditions.", "We reuse logits produced by the supervised fine-tuning forward pass and apply the nuclear norm to estimate sample utility and within-sample diversity. Low-dimensional representations and a historical buffer then identify redundancy across samples, enabling online selection of data that is more valuable for parameter updates."),
            ("Advantage", "Describe the concrete advantage and its boundary.", "Prioritizes backpropagation for high-value, non-redundant samples, increasing the density of effective updates within a fixed training budget and reducing the compute and time wasted on repeatedly training with homogeneous data."),
        ],
    },
    "A-07": {
        "heading": "A-07 On-Device Agents & Hardware Co-Design",
        "rows": [
            ("Field", "Instructions / suggested length", "Content"),
            ("Name", "Enter the technology-advantage name.", "On-Device Agents & Hardware Co-Design"),
            ("Method", "Describe the key method and applicable conditions.", "On resource-constrained devices such as the ESP32-S3, an event-driven Agent Loop connects sensors, local structured memory, and actuators, while MCP Client / Server interfaces provide access to authorized services and hardware endpoints."),
            ("Advantage", "Describe the concrete advantage and its boundary.", "Allows low-risk events to be handled closer to the device, reduces dependence on cloud-only connections, and lowers the cost of building one-off interfaces among sensors, actuators, and agent platforms."),
        ],
    },
    "A-08": {
        "heading": "A-08 Verifiable Feedback-Driven Continual Learning",
        "rows": [
            ("Field", "Instructions / suggested length", "Content"),
            ("Name", "Enter the technology-advantage name.", "Verifiable Feedback-Driven Continual Learning"),
            ("Method", "Describe the key method and applicable conditions.", "We anchor training direction with verifiable rewards, combine RLSD fine-grained self-distillation, NPO near-future policy guidance, and CoPD multi-expertise collaborative training, and record validators, rewards, model versions, and per-dimension evaluation results."),
            ("Advantage", "Describe the concrete advantage and its boundary.", "Provides denser learning signals that the current model can absorb more readily, reduces ineffective updates and conflicts when merging expertise, and makes continual model iteration more interpretable, measurable, and reversible."),
        ],
    },
}

# M2 canonicalizes the authored missing-module rows too. This keeps the
# generated modules on the same public field vocabulary as the translated
# existing modules, without touching prose or identifiers.
for _missing in MISSING_EN.values():
    _rows = _missing["rows"]
    _rows[0] = ("Entry", "Instructions / Suggested Length", "Content")
    for _index, _row in enumerate(_rows):
        if _row[0] == "Additional industry applications":
            _rows[_index] = ("Additional Industry Applications", _row[1], _row[2])
        if _row[1] == "Enter the technology-advantage name.":
            _rows[_index] = (_row[0], "Enter the technology advantage name.", _row[2])
        if _row[1] == "Describe the concrete advantage and its boundary.":
            _rows[_index] = (_row[0], "Describe the specific advantage and applicability boundaries.", _row[2])


DOCX_LABEL_NORMALIZATION = {
    "Fixed mapping": "Fixed Mapping",
    "Page title": "Page Title",
    "Organization": "Affiliation",
    "Official organization.": "Official institutional affiliation.",
    "Direction and related IDs": "Collaboration Direction & Related IDs",
    "Boundaries and notes": "Scope & Notes",
    "Completion note": "Instructions",
    "Corresponding content name": "Related Content Name",
    "Fixed detail-entry rule": "Fixed Detail Entry",
    "Home-page summary": "Homepage Summary",
    "Inner-page introduction": "Inner-Page Introduction",
    "One-sentence definition": "One-Sentence Definition",
    "Questions addressed": "Key Questions",
    "Main research content": "Main Research Content",
    "Application scenarios": "Application Scenarios",
    "Representative projects": "Representative Projects",
    "Additional notes": "Additional Notes",
    "Shared problem": "Shared Problem",
    "Individual boundaries": "Individual Boundaries",
    "Connection model": "Connection Method",
    "Relationship visual": "Relationship Visual",
    "Scenario-to-project mapping": "Scenarios & Project Mapping",
    "Project name": "Project Name",
    "Project image": "Project Image",
    "Source attributes": "Source / Evidence Metadata",
    "Fixed field": "Fixed Item",
    "Fixed content": "Fixed Content",
    "Shared home/partner introduction": "Shared Homepage and Partners-Page Intro",
    "Organization name": "Organization Name",
    "Logo file or location": "Logo File or Location",
    "Logo approved for public use": "Logo Public-Use Permission",
    "Title / role": "Title / Role",
    "Research interests": "Research Interests",
    "Short biography": "Short Bio",
    "Research directions": "Research Areas",
    "Representative projects / outputs": "Representative Projects / Outputs",
    "Personal link": "Personal Link",
    "Publication status": "Publication Status",
    "Collaboration target": "Collaboration Target",
    "Collaboration format": "Collaboration Format",
    "Target / scenario": "Suitable Target / Scenario",
    "Investment, process, and notes": "Investment, Process & Notes",
    "Recruitment target": "Recruitment Target",
    "Application method": "Application Method",
    "Current status": "Current Status",
    "Contact person": "Contact Person",
    "Social / booking": "Social / Booking",
    "What to provide": "What to Provide When Contacting",
    "What to provide when contacting": "What to Provide When Contacting",
    "Supported inquiries": "Matters We Respond To",
    "Expected response": "Expected Response",
    "Contact-person name.": "Contact person’s name.",
    "What to provide in the first contact.": "What to provide in the initial communication.",
    "State which inquiries can be handled.": "Specify the inquiries we can handle.",
}


def canonicalize_docx_labels(doc: Document) -> None:
    """Normalize exact label cells and stable heading text only."""
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells[:2]:
                current = norm(cell.text)
                if current in DOCX_LABEL_NORMALIZATION:
                    set_simple_cell(cell, DOCX_LABEL_NORMALIZATION[current])
    for paragraph in doc.paragraphs:
        current = norm(paragraph.text)
        if current == "R-06 Scenario-to-Project Mapping":
            paragraph.text = "R-06 Scenarios & Project Mapping"


def canonicalize_docx_terms(doc: Document) -> None:
    """Lock recurring technical wording in existing English prose."""
    replacements = {
        "Edge Computing (EDGE-AI)": "Edge Intelligence (EDGE-AI)",
        "On-device Vision": "On-Device Vision",
    }
    paragraphs = list(doc.paragraphs)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                paragraphs.extend(cell.paragraphs)
    for paragraph in paragraphs:
        for run in paragraph.runs:
            for old, new in replacements.items():
                if old in run.text:
                    run.text = run.text.replace(old, new)


HTML_B_LABEL_NORMALIZATION = {
    **DOCX_LABEL_NORMALIZATION,
    "Field": "Field",
    "Entry": "Entry",
    "One-sentence bio": "One-Sentence Bio",
    "One-Sentence bio": "One-Sentence Bio",
    "Short biography": "Short Bio",
    "Additional industry applications": "Additional Industry Applications",
}


def canonicalize_html_b_labels(raw: str) -> str:
    def replace(match: re.Match[str]) -> str:
        value = match.group(2)
        normalized = HTML_B_LABEL_NORMALIZATION.get(value, value)
        for prefix, canonical in {
            "Page title": "Page Title",
            "Homepage summary": "Homepage Summary",
            "Home-page summary": "Homepage Summary",
            "Inner-page introduction": "Inner-Page Introduction",
        }.items():
            if value.startswith(prefix + " |"):
                normalized = canonical + value[len(prefix):]
                break
        return f"{match.group(1)}{normalized}{match.group(3)}"

    return re.sub(r"(<b>)([^<]+)(</b>)", replace, raw)


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def section_table_map(doc: Document):
    """Return section -> ordered table objects, using stable headings."""
    out: dict[str, list] = defaultdict(list)
    current = "(before)"
    by_element = {t._element: t for t in doc.tables}
    for child in doc.element.body.iterchildren():
        if child.tag.endswith("}p"):
            p = Paragraph(child, doc)
            text = norm(p.text)
            if text and p.style.name.lower().startswith("heading"):
                m = SECTION_RE.search(text)
                if m:
                    current = m.group(1)
        elif child.tag.endswith("}tbl") and child in by_element:
            out[current].append(by_element[child])
    return out


def all_docx_xml_text(root) -> list[str]:
    return [str(x) for x in xpath_nodes(root, "//w:t/text()", text=True)]


def xpath_nodes(element, expression: str, *, text: bool = False):
    """Call lxml or python-docx XPath with the appropriate API."""
    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    try:
        return element.xpath(expression, namespaces=ns)
    except TypeError:
        # python-docx BaseOxmlElement already carries the w namespace and
        # rejects lxml's ``namespaces=`` keyword.
        return element.xpath(expression)


def replace_xml_text(root, mapping: dict[str, str]):
    """Replace exact w:t values, longest keys first; preserve run formatting."""
    for node in xpath_nodes(root, "//w:t"):
        value = node.text or ""
        if value in mapping:
            node.text = mapping[value]


def set_simple_cell(cell, value: str):
    cell.text = value


def set_section_row_content(doc: Document, section: str, row_label: str, value: str) -> None:
    """Set a stable row's content cell without relying on table indexes."""
    tables = section_table_map(doc).get(section, [])
    for table in tables:
        for row in table.rows:
            if row.cells and norm(row.cells[0].text) == row_label:
                if len(row.cells) < 3:
                    raise RuntimeError(f"{section} row {row_label!r} has no content cell")
                set_simple_cell(row.cells[2], value)
                return
    raise RuntimeError(f"Cannot locate {section} row {row_label!r}")


def replace_run_exact_text(doc: Document, mapping: dict[str, str]) -> None:
    """Catch exact values held in python-docx runs after XML-level mapping."""
    paragraphs = list(doc.paragraphs)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                paragraphs.extend(cell.paragraphs)
    for paragraph in paragraphs:
        for run in paragraph.runs:
            if run.text in mapping:
                run.text = mapping[run.text]


def build_diff_report():
    zh = Document(ZH_DOCX)
    en = Document(EN_DOCX)
    zmap = section_table_map(zh)
    emap = section_table_map(en)
    sections_zh = list(zmap)
    sections_en = list(emap)
    only_zh = [s for s in sections_zh if s not in emap]
    only_en = [s for s in sections_en if s not in zmap]

    lines = [
        "# 实验室官网语言对齐差异清单（M0/M1 基线）",
        "",
        "本清单按稳定章节编号和实体编号生成；不使用页码、顶层段落数或表序作为配对主键。裁决规则：中文 DOCX 为内容母版。",
        "",
        "## 文件基线",
        "",
        f"- 中文 DOCX：{len(zh.paragraphs)} 个顶层段落、{len(zh.tables)} 张表；章节：{', '.join(sections_zh)}。",
        f"- 英文 DOCX：{len(en.paragraphs)} 个顶层段落、{len(en.tables)} 张表；章节：{', '.join(sections_en)}。",
        f"- 中文 HTML：`lang=zh-CN`，38 个 `data-code`，7 个页签。",
        f"- 英文 HTML：原稿 `lang=zh-CN`，38 个 `data-code`，7 个页签。",
        "",
        "## 仅中文 DOCX 存在的章节",
        "",
    ]
    lines.extend(f"- `{s}`：英文 DOCX 缺失，必须按中文母版翻译补齐。" for s in only_zh)
    lines += ["", "## 仅英文 DOCX 存在的章节", ""]
    lines.extend(f"- `{s}`：中文 DOCX 不存在；按母版裁决时不保留为独有章节。" for s in only_en)
    lines += ["", "## 同编号内容冲突", "", "| 稳定编号 | 中文母版 | 英文原稿 | 裁决 |", "|---|---|---|---|"]
    lines += [
        "| H-04-01/02/03 | P-07-06 / P-07-08 / P-07-05 | P-03 / P-04 / P-05 | 采用中文母版编号，并同步四份修订副本 |",
        "| H-06/T-02 | 中文 HTML 仅展示 PI | 英文 HTML 展示 Chaw、Jeff Wang、Wendy 三档案；中文 DOCX 有三档案 | 以中文 DOCX 三档案为准，补齐中文 HTML |",
        "| R-06 | 中文 DOCX 有五项场景映射 | 英文 DOCX 缺失；英文 HTML 仅有不完整四项 | 采用中文 DOCX 五项并完整翻译 |",
        "| A-04 至 A-08 | 中文 DOCX 有五个前沿技术模块 | 英文 DOCX 缺失 | 采用中文 DOCX 并翻译补齐 |",
        "| 版本标记 | 中文 HTML `v3-contract-2` | 英文 HTML `v3-contract-1` | 统一为 `v3-contract-2` |",
    ]
    lines += [
        "",
        "## 稳定实体差异矩阵（原始文件）",
        "",
        "状态只按稳定章节/实体键记录；不以页码、顶层段落数、表序或视觉位置配对。",
        "",
        "| 稳定实体键 | 中英文原稿状态 | 证据/裁决 |",
        "|---|---|---|",
        "| H-01…H-03、H-05、H-07 | 两边存在 | 同编号，无已知内容冲突 |",
        "| H-04-01/02/03 | 同编号内容冲突 | 首页精选项目采用中文母版 P-07-06 / P-07-08 / P-07-05 |",
        "| R-01…R-05 | 两边存在 | 同编号，无已知结构缺口 |",
        "| R-06 | 仅中文存在 | 英文 DOCX 缺失；英文 HTML 映射不完整，按母版补齐 20 个项目 ID |",
        "| P-01/P-02/P-07/P-08 | 两边存在 | P-01 证据限定语按中文母版裁决 |",
        "| P-03…P-07-17 | 两边存在 | 项目正文保留来源、归属、指标待核验等限定语 |",
        "| A-01…A-03 | 两边存在 | 标题与记录名称按不同槽位保留 |",
        "| A-04…A-08 | 仅中文存在 | 英文 DOCX 缺失，按母版补齐五个完整模块 |",
        "| N-01/N-02-01…N-02-12 | 两边存在 | 伙伴标识槽按稳定槽键对齐 |",
        "| T-01/T-02-01…T-02-03/T-03/T-04 | 同编号内容冲突 | 中文 HTML 原稿仅 PI；按中文 DOCX 三档案同步两份 HTML |",
        "| C-01…C-06 | 两边存在 | 联系字段按稳定 C 编号对齐，未新增未经确认表单 |",
        "",
        "## M1 生成结果快照",
        "",
        "- 英文 DOCX 修订副本：65 张表；章节顺序包含 R-06、A-04、A-05、A-06、A-07、A-08，且 A 模块按母版顺序排列。",
        "- 英文 HTML 修订副本：`lang=en`、38 个 `data-code`、7 个页签；T-02 含 `profile-chaw`、`profile-jeff`、`profile-wendy` 三个稳定档案键。",
        "- 中文 HTML 修订副本：`lang=zh-CN`、38 个 `data-code`、7 个页签；T-02 同样含三个稳定档案键；普通分类标题不再显示隐藏英文副本。",
        "- 英文显示层 CJK 扫描：仅保留机器路径 `docs/项目与优势.md`；该路径按既定机器标识例外，不属于可见自然语言。",
        "",
        "## 复核要求",
        "",
        "- 生成修订副本后重新运行本清单脚本；稳定实体矩阵中的缺口与冲突必须有对应裁决，不能静默跳过。",
        "- 任一新增项目、人名、指标、金额、年份、合作关系或删除证据限定语，均视为失败。",
    ]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def insert_missing_sections(en_doc: Document):
    """Insert R-06 and A-04..A-08 before the corresponding existing headings."""
    zh_doc = Document(ZH_DOCX)
    zh_sections = section_table_map(zh_doc)
    en_body = en_doc.element.body
    # Existing target paragraphs in the English document.
    targets = {}
    for child in en_body.iterchildren():
        if not child.tag.endswith("}p"):
            continue
        p = Paragraph(child, en_doc)
        text = norm(p.text)
        m = SECTION_RE.search(text)
        if m and m.group(1) in {"P-01", "N-01"}:
            targets[m.group(1)] = child

    for group, before in [(["R-06"], "P-01"), (["A-04", "A-05", "A-06", "A-07", "A-08"], "N-01")]:
        elements = []
        for section in group:
            source_heading = None
            for child in zh_doc.element.body.iterchildren():
                if not child.tag.endswith("}p"):
                    continue
                p = Paragraph(child, zh_doc)
                if SECTION_RE.search(norm(p.text)) and SECTION_RE.search(norm(p.text)).group(1) == section:
                    source_heading = child
                    break
            if source_heading is None:
                raise RuntimeError(f"Missing source heading {section}")
            heading = copy.deepcopy(source_heading)
            # Set heading text deterministically while preserving style.
            for node in xpath_nodes(heading, ".//w:t"):
                node.text = MISSING_EN[section]["heading"]
            elements.append(heading)
            # Find the source table belonging to this section.
            source_table = zh_sections[section][0]
            table = copy.deepcopy(source_table._element)
            ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
            rows = MISSING_EN[section]["rows"]
            cells = xpath_nodes(table, ".//w:tc")
            expected = sum(len(row) for row in rows)
            if len(cells) < expected:
                raise RuntimeError(f"Unexpected table shape for {section}: {len(cells)} < {expected}")
            pos = 0
            for row in rows:
                for value in row:
                    tc = cells[pos]
                    pos += 1
                    text_nodes = xpath_nodes(tc, ".//w:t")
                    if text_nodes:
                        text_nodes[0].text = value
                        for extra in text_nodes[1:]:
                            extra.text = ""
                    else:
                        run = etree.SubElement(etree.SubElement(tc, f"{{{ns['w']}}}p"), f"{{{ns['w']}}}r")
                        etree.SubElement(run, f"{{{ns['w']}}}t").text = value
            elements.append(table)
        target = targets[before]
        # ``addprevious`` inserts immediately before the target. Iterating in
        # source order therefore preserves the mother-document order
        # A-04 → A-05 → A-06 → A-07 → A-08.
        for element in elements:
            target.addprevious(element)


def set_docx_table_grid(table, widths: tuple[int, ...]) -> None:
    """Apply deterministic fixed-width geometry to one output table."""
    if len(widths) != len(table.columns):
        raise RuntimeError(f"Table width count mismatch: {len(widths)} != {len(table.columns)}")
    total = sum(widths)
    table.autofit = False
    tbl_pr = table._tbl.tblPr
    tbl_w = tbl_pr.find(qn("w:tblW"))
    if tbl_w is None:
        tbl_w = OxmlElement("w:tblW")
        tbl_pr.insert(0, tbl_w)
    tbl_w.set(qn("w:w"), str(total))
    tbl_w.set(qn("w:type"), "dxa")
    layout = tbl_pr.find(qn("w:tblLayout"))
    if layout is None:
        layout = OxmlElement("w:tblLayout")
        tbl_pr.append(layout)
    layout.set(qn("w:type"), "fixed")

    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width in widths:
        column = OxmlElement("w:gridCol")
        column.set(qn("w:w"), str(width))
        grid.append(column)
    for row in table.rows:
        for index, cell in enumerate(row.cells):
            tc_pr = cell._tc.get_or_add_tcPr()
            tc_w = tc_pr.find(qn("w:tcW"))
            if tc_w is None:
                tc_w = OxmlElement("w:tcW")
                tc_pr.insert(0, tc_w)
            tc_w.set(qn("w:w"), str(widths[index]))
            tc_w.set(qn("w:type"), "dxa")


def normalize_english_docx_geometry(doc: Document) -> None:
    """Give translated labels enough width to remain readable in Word."""
    three_column = (1800, 2600, 4960)
    four_column = {
        "P-02": (1200, 2700, 2300, 3160),
        "N-02": (1400, 2700, 3000, 2260),
        "T-03": (2300, 1100, 1800, 4160),
        "C-02": (1300, 2100, 2900, 3060),
        "C-03": (1300, 2300, 2600, 3160),
    }
    section_map = section_table_map(doc)
    for section, tables in section_map.items():
        for table in tables:
            columns = len(table.columns)
            if columns == 4:
                widths = four_column.get(section, (1300, 2200, 2700, 3160))
            elif columns == 3:
                widths = three_column
                if section == "H-03":
                    widths = (1500, 3900, 3960)
                elif section == "H-04":
                    widths = (1500, 3600, 4260)
            elif columns == 2:
                widths = (1800, 7560)
            else:
                raise RuntimeError(f"Unexpected English DOCX column count in {section}: {columns}")
            set_docx_table_grid(table, widths)


def normalize_english_section_heading_colors(doc: Document) -> None:
    """Keep every black section bar readable after cloning source headings."""
    for paragraph in doc.paragraphs:
        if not SECTION_RE.search(norm(paragraph.text)):
            continue
        for run in paragraph.runs:
            run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
            run.font.bold = True


def normalize_docx_row_heights(doc: Document) -> None:
    """Keep OOXML row heights integer-valued for Office CLI compatibility."""
    for node in xpath_nodes(doc.element.body, ".//w:trHeight"):
        raw_value = node.get(qn("w:val"))
        if raw_value is None:
            continue
        try:
            numeric = float(raw_value)
        except ValueError:
            continue
        if not numeric.is_integer():
            node.set(qn("w:val"), str(int(round(numeric))))


def clean_english_docx():
    doc = Document(EN_DOCX)
    # Insert missing content before text replacement; cloned tables use the
    # same geometry and styles as the Chinese source.
    insert_missing_sections(doc)

    # Apply exact translations to all visible XML text nodes.
    root = etree.fromstring(doc.element.body.xml.encode("utf-8"))
    replace_xml_text(root, EN_MAP)
    # doc.element.body is already the live element; repeat replacement on it.
    replace_xml_text(doc.element.body, EN_MAP)
    replace_run_exact_text(doc, EN_MAP)
    canonicalize_docx_labels(doc)
    canonicalize_docx_terms(doc)

    # Official English display names and the mother-version homepage project IDs.
    for table in section_table_map(doc)["H-04"]:
        set_simple_cell(table.cell(1, 2), "P-07-06")
        set_simple_cell(table.cell(2, 2), "P-07-08")
        set_simple_cell(table.cell(3, 2), "P-07-05")

    # Stable row keys, not table positions, resolve the known source conflicts.
    set_section_row_content(doc, "R-02", "Representative Projects", "P-07-01, P-07-02, P-07-06")
    set_section_row_content(doc, "R-03", "Representative Projects", "P-05, P-07-03, P-07-08, P-07-09")
    set_section_row_content(doc, "R-04", "Representative Projects", "P-03, P-04, P-07-04, P-07-05, P-07-10")
    # T-02 is one logical section containing three stable profile tables. Do
    # not use a global person-name replacement: the Chinese/English paired
    # source cell would otherwise become ``Dr. Jeff Wang / Dr. Jeff Wang``.
    t02_tables = section_table_map(doc).get("T-02", [])
    profile_names = ["Dr. Chaw Jun Kit", "Dr. Jeff Wang", "Wendy Leong Pooi Yan"]
    profile_index = 0
    for table in t02_tables:
        for row in table.rows:
            if row.cells and norm(row.cells[0].text) == "Name":
                if profile_index >= len(profile_names):
                    raise RuntimeError("Unexpected extra T-02 profile name row")
                set_simple_cell(row.cells[2], profile_names[profile_index])
                profile_index += 1
    if profile_index != len(profile_names):
        raise RuntimeError(f"Expected {len(profile_names)} T-02 profile names, found {profile_index}")
    set_section_row_content(
        doc,
        "P-01",
        "Inner-Page Introduction",
        "Our projects represent the successful leap from academic breakthroughs to industrial applications. Backed by national grants and corporate co-funding (e.g., Advantech, HILTI), the HI Lab delivers highly adaptable AI systems tailored for predictive maintenance, edge deployment, and LLM orchestration. These solutions directly serve manufacturing enterprises, healthcare providers, and government policymakers. The directory also includes 13 company/team industry cases presented on the original KOALA SYNC TECH website as capability signals; these cases are not evidence of individually owned contributions, client relationships, or verified commercial metrics, and the statistical basis of all percentage metrics remains to be verified.",
    )

    # Remove Chinese-only category labels from the Chinese-named source that
    # may remain in a compound cell after exact run replacement.
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                if cell.text.strip() == "AI Solutions｜人工智能解决方案":
                    set_simple_cell(cell, "AI Solutions")
                elif cell.text.strip() == "Edge Intelligence｜边缘智能":
                    set_simple_cell(cell, "Edge Intelligence")
                elif cell.text.strip() == "Custom Digital Products｜定制数字产品":
                    set_simple_cell(cell, "Custom Digital Products")
                elif cell.text.strip() == "Digital Transformation｜数字化升级":
                    set_simple_cell(cell, "Digital Transformation")

    normalize_english_docx_geometry(doc)
    normalize_english_section_heading_colors(doc)
    normalize_docx_row_heights(doc)
    doc.save(OUT_EN_DOCX)


def clean_chinese_docx():
    doc = Document(ZH_DOCX)
    # Remove ordinary English category duplicates; technical terms and official
    # names remain untouched under the explicit whitelist policy.
    replacements = {
        "AI Solutions｜人工智能解决方案": "人工智能解决方案",
        "Edge Intelligence｜边缘智能": "边缘智能",
        "Custom Digital Products｜定制数字产品": "定制数字产品",
        "Digital Transformation｜数字化升级": "数字化升级",
    }
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for old, new in replacements.items():
                    if cell.text.strip() == old:
                        set_simple_cell(cell, new)
    for paragraph in doc.paragraphs:
        text = paragraph.text.strip()
        for old, new in replacements.items():
            # These category headings are top-level paragraphs, not table
            # cells; keep the count suffix while removing the English label.
            if text.startswith(old):
                suffix = text[len(old):]
                paragraph.text = new + suffix
                break
    normalize_docx_row_heights(doc)
    doc.save(OUT_ZH_DOCX)


def replace_html_texts(raw: str, mapping: dict[str, str]) -> str:
    # Replace only text/attribute values, never scripts or base64. Longest first
    # prevents a short phrase from corrupting a compound field.
    for old in sorted(mapping, key=len, reverse=True):
        raw = raw.replace(old, mapping[old])
    return raw


def clean_english_html():
    raw = EN_HTML.read_text(encoding="utf-8")
    # Preserve the exact machine path while translating surrounding prose.
    path_token = "__LAB_PROJECT_ADVANTAGE_PATH__"
    raw = raw.replace("docs/项目与优势.md", path_token)
    # A few short Chinese labels are valid DOCX cell keys but unsafe as raw
    # HTML substring replacements (e.g. 项目 inside the machine path or 方向
    # inside 合作方向). Translate their longer phrases first, then handle only
    # standalone HTML text tokens below.
    html_mapping = dict(EN_MAP)
    for unsafe in {
        "首页", "项目", "技术优势", "合作伙伴", "团队", "联系合作",
        "方向", "优势", "内容", "编号", "投入：", "流程：",
    }:
        html_mapping.pop(unsafe, None)
    # Global exact replacements handle labels, metadata, aria text and names.
    raw = replace_html_texts(raw, html_mapping)
    for old, new in {
        ">首页<": ">Home<",
        ">项目<": ">Projects<",
        ">技术优势<": ">Technology Advantages<",
        ">合作伙伴<": ">Partners<",
        ">团队<": ">Team<",
        ">联系合作<": ">Contact<",
        ">方向<": ">Direction<",
        ">优势<": ">Advantage<",
        ">内容<": ">Content<",
        ">编号<": ">ID<",
    }.items():
        raw = raw.replace(old, new)
    # Category labels are ordinary UI text, not technical terms; remove their
    # hidden English spans as well as the visible bilingual heading.
    for label in ("AI Solutions", "Edge Intelligence", "Custom Digital Products", "Digital Transformation"):
        raw = raw.replace(f'<span lang="en">{label}</span>｜', "")
    # The home cards intentionally retain an English span next to the source
    # label. Remove the Chinese prefix without touching surrounding structure.
    for source_label in ("技术优势", "项目", "合作伙伴", "团队", "联系合作"):
        raw = re.sub(
            rf'(<h2[^>]*>)\s*{re.escape(source_label)}\s*(?=<span\s+lang="en">)',
            r'\1',
            raw,
        )
    raw = raw.replace(path_token, "docs/项目与优势.md")
    raw = canonicalize_html_b_labels(raw)
    for old, new in {
        "Contact-person name.": "Contact person’s name.",
        "What to provide in the first contact.": "What to provide in the initial communication.",
        "State which inquiries can be handled.": "Specify the inquiries we can handle.",
        "Official organization.": "Official institutional affiliation.",
        "Direction and related IDs": "Collaboration Direction &amp; Related IDs",
        "Boundaries and notes": "Scope &amp; Notes",
    }.items():
        raw = raw.replace(old, new)
    raw = raw.replace("Edge Computing (EDGE-AI)", "Edge Intelligence (EDGE-AI)")
    raw = raw.replace("On-device Vision", "On-Device Vision")
    # Remove bilingual shell duplicates after the English copy is generated.
    # These are visible headings, not machine identifiers or content values.
    raw = raw.replace('<h2>Vision <span lang="en">Vision</span></h2>', '<h2>Vision</h2>')
    raw = raw.replace('<h2>Research Areas <span lang="en">Research</span></h2>', '<h2>Research Directions</h2>')
    raw = raw.replace('<h2>Three-direction relationship</h2>', '<h2>Relationship Among the Three Directions</h2>')
    # Canonicalize the page-level research label without touching field labels
    # such as “Research Areas” inside profile and project records.
    raw = raw.replace('id="tab-research" role="tab" aria-selected="false" aria-controls="panel-research" tabindex="-1">Research Areas</button>', 'id="tab-research" role="tab" aria-selected="false" aria-controls="panel-research" tabindex="-1">Research Directions</button>')
    raw = raw.replace('<header class="pagehead"><div><small>PAGE R</small><h1>Research Areas</h1></div>', '<header class="pagehead"><div><small>PAGE R</small><h1>Research Directions</h1></div>')
    raw = raw.replace('<html lang="zh-CN">', '<html lang="en">', 1)
    raw = raw.replace("实验室官网｜English v3 内容线框预览", "Laboratory Website | English v3 Content Wireframe Preview")
    # The Chinese mother selects these three home-page projects.
    raw = raw.replace("已选择三个互不重复的项目编号：P-03、P-04、P-05；标题读取对应项目的“项目名称”，摘要读取“R 结果”。", "Three distinct project IDs are selected: P-07-06, P-07-08, and P-07-05; titles read the corresponding project names and summaries read the R results.")
    raw = raw.replace("H-04-01 · P-03", "H-04-01 · P-07-06")
    raw = raw.replace("H-04-02 · P-04", "H-04-02 · P-07-08")
    raw = raw.replace("H-04-03 · P-05", "H-04-03 · P-07-05")
    # Stable section/field replacements for the mother-version project sets.
    def replace_section_field(source: str, section: str, label: str, value: str) -> str:
        section_re = re.compile(
            rf'(<article[^>]*data-code="{re.escape(section)}"[^>]*>.*?<b>{re.escape(label)}[^<]*</b>)(.*?)(</li>)',
            re.S,
        )
        updated, count = section_re.subn(rf'\1{value}\3', source, count=1)
        if count != 1:
            raise RuntimeError(f"Cannot locate HTML field {section}.{label}")
        return updated

    raw = replace_section_field(raw, "R-02", "Representative Projects", "P-07-01, P-07-02, P-07-06")
    raw = replace_section_field(raw, "R-03", "Representative Projects", "P-05, P-07-03, P-07-08, P-07-09")
    raw = replace_section_field(raw, "R-04", "Representative Projects", "P-03, P-04, P-07-04, P-07-05, P-07-10")
    p01_intro = "Our projects represent the successful leap from academic breakthroughs to industrial applications. Backed by national grants and corporate co-funding (e.g., Advantech, HILTI), the HI Lab delivers highly adaptable AI systems tailored for predictive maintenance, edge deployment, and LLM orchestration. These solutions directly serve manufacturing enterprises, healthcare providers, and government policymakers. The directory also includes 13 company/team industry cases presented on the original KOALA SYNC TECH website as capability signals; these cases are not evidence of individually owned contributions, client relationships, or verified commercial metrics, and the statistical basis of all percentage metrics remains to be verified."
    raw = replace_section_field(raw, "P-01", "Inner-Page Introduction", p01_intro)
    # Use the full mother-version R-06 mapping; the prior English HTML had a
    # shortened placeholder and omitted several confirmed project mappings.
    old_r06 = re.compile(r'<article class="block" data-code="R-06">.*?</article>', re.S)
    new_r06 = '''<article class="block" data-code="R-06"><div class="top"><span class="code">R-06</span><p class="meta">Use “scenario name: P ID”; do not repeat project descriptions</p></div><h2>Scenarios &amp; Project Mapping</h2><ul class="field-list one"><li class="field-item"><b>HEALTH mapping</b>Early Prediction of NCDs: P-07-01; Elderly Mental Health Monitoring: P-07-02; Personalized Fitness Guidance: P-07-06.</li><li class="field-item"><b>EDGE-AI mapping</b>Smart Grocer Produce Recognition: P-05; Agriculture 4.0 Drone Mapping: P-07-03; Facial Recognition Access Control: P-07-08; Game Visual Guide: P-07-09.</li><li class="field-item"><b>AGENT mapping</b>AI-RAG Digital Concierge: P-03; National Address System: P-04; Scam Monitoring: P-07-04; DingTalk Office Assistant: P-07-05; TikTok Lead Generation &amp; Sales: P-07-10.</li><li class="field-item"><b>Additional Industry Applications</b>AI Art Image Generation Platform: P-07-07; Merace Metaverse Gaming Platform: P-07-11; Intelligent Insurance Services and Online Claims Platform: P-07-12; AI Social Commerce App: P-07-13; O2O Intelligent Matching and Activity-based Social Platform: P-07-14; RiceUp Local Food Delivery Platform: P-07-15; Mead Johnson Marketing Management System: P-07-16; Custom Warehouse Management System (WMS): P-07-17.</li></ul></article>'''
    raw = old_r06.sub(new_r06, raw, count=1)
    # Keep the source path as a machine identifier; all prose around it is
    # English and the QA scanner will whitelist this exact path only.
    OUT_EN_HTML.write_text(raw, encoding="utf-8")


def profile_section_html(profile_id: str, heading: str, fields: list[tuple[str, str]], photo_note: str = "Not provided") -> str:
    items = "".join(f'<li class="field-item"><b>{html_lib.escape(label)}</b>{value}</li>' for label, value in fields)
    return f'<section class="profile-entry" aria-labelledby="{profile_id}"><h3 id="{profile_id}">{heading}</h3><div class="split"><ul class="field-list one">{items}</ul><div class="media-box missing"><span><b>照片</b><br/>{photo_note}</span></div></div></section>'


def clean_chinese_html():
    raw = ZH_HTML.read_text(encoding="utf-8")
    # Remove ordinary bilingual UI duplicates while retaining technical names.
    raw = raw.replace('<span lang="en">Vision</span>', "")
    raw = raw.replace('<span lang="en">Research</span>', "")
    raw = raw.replace('<span lang="en">Technology Advantages</span>', "")
    raw = raw.replace('<span lang="en">Projects</span>', "")
    raw = raw.replace('<span lang="en">Partners</span>', "")
    raw = raw.replace('<span lang="en">Team</span>', "")
    raw = raw.replace('<span lang="en">Contact</span>', "")
    for old, new in {
        "AI Solutions｜人工智能解决方案": "人工智能解决方案",
        "Edge Intelligence｜边缘智能": "边缘智能",
        "Custom Digital Products｜定制数字产品": "定制数字产品",
        "Digital Transformation｜数字化升级": "数字化升级",
        "Logo文件或位置说明": "标识文件或位置说明",
        "Logo是否允许公开使用": "标识是否允许公开使用",
    }.items():
        raw = raw.replace(old, new)
    # Category labels are ordinary UI text, not technical terms; remove their
    # hidden English spans as well as the visible bilingual heading.
    for label in ("AI Solutions", "Edge Intelligence", "Custom Digital Products", "Digital Transformation"):
        raw = raw.replace(f'<span lang="en">{label}</span>｜', "")
    # Synchronize the three home cards with the Chinese DOCX mother version.
    raw = raw.replace("H-04-01 · P-07-06", "H-04-01 · P-07-06")
    raw = raw.replace("H-04-02 · P-07-08", "H-04-02 · P-07-08")
    raw = raw.replace("H-04-03 · P-07-05", "H-04-03 · P-07-05")

    # The Chinese HTML originally displayed only the PI. Add the two other
    # profiles present in the authoritative Chinese DOCX so all four artifacts
    # expose the same team entities.
    if 'id="profile-chaw"' not in raw:
        jeff = profile_section_html(
            "profile-jeff",
            "王鸿清（Dr. Jeff Wang）",
            [
                ("姓名 / 职称或角色 / 单位", "王鸿清 Dr. Jeff Wang<br>首席技术官（CTO）<br>未提供"),
                ("研究兴趣 / 短简介", "未提供<br>未提供"),
                ("研究方向", "未提供"),
                ("代表项目/成果", "未提供"),
                ("个人链接", "未提供"),
                ("补充", "未提供"),
            ],
            "未提供",
        )
        wendy = profile_section_html(
            "profile-wendy",
            "Wendy Leong Pooi Yan · Mobiva 首席执行官",
            [
                ("姓名 / 职称或角色 / 单位", "Wendy Leong Pooi Yan<br>Mobiva 首席执行官<br>Mobiva"),
                ("研究兴趣 / 短简介", "危机管理人工智能、疫情预测、企业移动化、云端决策支持。<br>Wendy Leong 是企业移动与应急管理平台 Mobiva 的首席执行官，同时在 IVI-Edge Lab 攻读博士学位。她将商业技术领导力与前沿人工智能研究连接起来，重点研究人工智能在疫情预测中的协同作用，以及用于灾害响应的实时、包容性人工智能，并将学术框架转化为可扩展的企业级 B2B 解决方案。"),
                ("研究方向", "R-02 HEALTH、R-04 AGENT"),
                ("代表项目/成果", "《疫情预测的量子跃迁》（书籍章节，2025）；通过 Mobiva 实现企业集成。"),
                ("个人链接", '<a href="https://www.linkedin.com/in/wendyleong99/" target="_blank" rel="noopener noreferrer">LinkedIn 主页</a><br><a href="https://mobiva.net/" target="_blank" rel="noopener noreferrer">Mobiva 官方网站</a>'),
                ("补充", "拥有丰富的企业高管级 B2B 行业经验，推动实验室的商业技术转移与真实灾害管理落地。"),
            ],
            "待提供",
        )
        # The Chinese source has the PI as one flat split block. Wrap that
        # existing block as profile-chaw, then append the two authoritative
        # profiles. Slice by the known T-02/T-03 and split closing markers so
        # the embedded base64 image is copied byte-for-byte.
        t02_start = raw.find('<article class="block" data-code="T-02">')
        t03_start = raw.find('<article class="block quiet" data-code="T-03">', t02_start)
        if t02_start < 0 or t03_start < 0:
            raise RuntimeError("Cannot locate Chinese T-02/T-03 boundaries")
        split_start = raw.find('<div class="split">', t02_start, t03_start)
        split_close_marker = '</div></div>\n        </article>'
        split_end = raw.find(split_close_marker, split_start, t03_start)
        if split_start < 0 or split_end < 0:
            raise RuntimeError("Cannot locate Chinese T-02 PI split block")
        existing_split = raw[split_start : split_end + len('</div></div>')]
        pi = (
            '<section class="profile-entry" aria-labelledby="profile-chaw">'
            '<h3 id="profile-chaw">课题负责人（PI）· 周俊杰 Dr. Chaw Jun Kit</h3>'
            f'{existing_split}</section>'
        )
        profile_list = '<div class="profile-list">' + pi + jeff + wendy + '</div>'
        raw = raw[:split_start] + profile_list + raw[split_end + len('</div></div>'):]
    OUT_ZH_HTML.write_text(raw, encoding="utf-8")


def main():
    clean_chinese_docx()
    clean_english_docx()
    clean_chinese_html()
    clean_english_html()
    build_diff_report()
    print("Wrote:")
    for path in [REPORT, OUT_ZH_DOCX, OUT_EN_DOCX, OUT_ZH_HTML, OUT_EN_HTML]:
        print(path)


if __name__ == "__main__":
    main()
